import type { HumanProvisioningNode } from "./types";

/** Auto-generated by scripts/sync-wiring-paper-from-docs.py - do not edit by hand. */
export const HUMAN_PROVISIONING_NODES: HumanProvisioningNode[] = [
{
    node: "sending_domain",
    requiresToExist: "DNS delegation on the firm's zone, or pool subdomain attach, SPF/DKIM publish, and warmup calendar-time.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the branded-domain setup and warmup dependency.",
    relatedFunctionSeats: ["C1", "C7"],
  },
{
    node: "dkim_keyset",
    requiresToExist: "DKIM DNS TXT/CNAME publish or domain-control verification on the firm zone.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the domain-authentication setup dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "dmarc_policy",
    requiresToExist: "DMARC DNS policy and reporting address publish on the firm From domain.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the From-domain policy setup dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "return_path_domain",
    requiresToExist: "Custom MAIL FROM / Return-Path DNS and bounce-domain delegation.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the bounce-domain setup dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "sending_identity_binding",
    requiresToExist: "Firm-approved sending domain and From identity, with completed domain authentication.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the selected sending identity and its upstream domain-auth readiness.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "from_identity",
    requiresToExist: "Firm-approved visible From name, local part, and alignable domain choice.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the firm-facing identity approval dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "reply_route",
    requiresToExist: "Firm mailbox forwarding/delegation or monitored Reply-To authorization when replies are not platform-captured.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the reply capture or firm-mailbox routing dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "ip_pool_tier",
    requiresToExist: "Dedicated IP procurement / provider approval when a dedicated tier is required; shared pools remain house-managed.",
    scope: "per-firm when dedicated; house-global when shared",
    inheritedBy: "Every path touching this node inherits the selected pool tier and any provider approval dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "warmup_schedule",
    requiresToExist: "Calendar-time warmup and receiver acceptance signals for the selected domain/IP posture.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the ramp-time dependency before full volume can exist.",
    relatedFunctionSeats: ["C1", "C7"],
  },
{
    node: "provider_reputation_feed",
    requiresToExist: "Postmaster/FBL enrollment and domain verification where the provider requires it.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the provider reputation-signal enrollment dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "sms_sender_registration",
    requiresToExist: "TCR/brand/campaign registration.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the SMS registry approval dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "carrier_throughput_tier",
    requiresToExist: "Carrier/TCR throughput tier approval.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the carrier-approved capacity dependency.",
    relatedFunctionSeats: ["C1"],
  },
{
    node: "escrow_ledger_entry",
    requiresToExist: "Signed or accepted contingent commercial terms for the firm.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the commercial-terms acceptance dependency.",
    relatedFunctionSeats: ["C6"],
  },
{
    node: "held_balance",
    requiresToExist: "Firm payment authorization/funding and provider hold or capture settlement.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the firm-funding and settlement dependency.",
    relatedFunctionSeats: ["C6"],
  },
{
    node: "provider_payment_identity",
    requiresToExist: "Payment processor account/KYB setup, firm payment method mandate, and Connect/bank reference provisioning.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the processor identity and firm-payment authorization dependency.",
    relatedFunctionSeats: ["C6"],
  },
{
    node: "enrichment_root",
    requiresToExist: "Firm-controlled public URL or public listing identity availability/verification when absent or disputed.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the public-root availability and verification dependency.",
    relatedFunctionSeats: ["C5"],
  },
{
    node: "crawl_permission",
    requiresToExist: "Firm/site-admin crawl permission change when robots.txt or directives block required public paths.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the public-site permission dependency when crawl is blocked.",
    relatedFunctionSeats: ["C5"],
  },
{
    node: "campaign_proxy_aggregate",
    requiresToExist: "Per-firm ad-platform/export access authorization when proxy aggregate import is required.",
    scope: "per-firm",
    inheritedBy: "Every path touching this node inherits the ad-platform access/export dependency.",
    relatedFunctionSeats: ["C7"],
  },
{
    node: "counsel_gate",
    requiresToExist: "Counsel clearance for MT/MSB/payment rail posture.",
    scope: "counsel",
    inheritedBy: "Every path touching this node inherits the legal clearance dependency; engineering records state but does not create clearance.",
    relatedFunctionSeats: ["C6"],
  }
];

export function getHumanProvisioningNode(nodeName: string): HumanProvisioningNode | undefined {
  return HUMAN_PROVISIONING_NODES.find((node) => node.node === nodeName);
}
