import { writeFileSync } from "node:fs";
import { flattenHolonCatalog, HOLON_CATALOG_ROOTS } from "../src/app/components/docs/holonCatalogTree.ts";

const entries = flattenHolonCatalog(HOLON_CATALOG_ROOTS);

const contents = `import type { HolonRegistration } from "../../context/DocsRegistryContext";

/** Pre-flattened holon catalog for Systems Register — generated by scripts/generate-holon-catalog-flat.mts */
export const HOLON_CATALOG_ENTRIES: HolonRegistration[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(new URL("../src/app/components/docs/holonCatalogFlat.ts", import.meta.url), contents);
console.log(`Wrote ${entries.length} holon catalog entries.`);
