#!/usr/bin/env python3
"""Parse docs/register/enrichment + furnish into Register theory TS modules."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENRICH_DIR = ROOT / "docs" / "register" / "enrichment"
FURNISH_DIR = ROOT / "docs" / "register" / "furnish"
OUT_DIR = ROOT / "src" / "app" / "register" / "theory" / "enrichment"

HEADING_RE = re.compile(r"^### `([^`]+)`\s+[—–-]\s+(.+)$", re.MULTILINE)
GEN = "/** Auto-generated by scripts/sync-persona-cants-furnish-from-docs.py — do not edit by hand. */"

SUBJECTS = [
    ("consultant", "Consultant", "consultant-cants.md", "consultant-furnish.md"),
    ("operator", "Operator", "operator-cants.md", "operator-furnish.md"),
    ("contact", "Engagement contact", "contact-cants.md", "contact-furnish.md"),
]


def ts_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def parse_surface_ids(raw: str) -> list[str]:
    raw = raw.strip()
    try:
        parsed = json.loads(raw.replace("'", '"'))
        if isinstance(parsed, list):
            return [str(x) for x in parsed]
    except json.JSONDecodeError:
        pass
    return [p.strip().strip('"').strip("'") for p in re.findall(r'"([^"]+)"|\'([^\']+)\'', raw) if p[0] or p[1]]


def field_line(lines: list[str], label: str) -> str:
    prefix = f"- **{label}:**"
    for line in lines:
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    return ""


def field_block(lines: list[str], label: str) -> str:
    """Single-line or continued lines after `- **label:**` until next `- **`."""
    prefix = f"- **{label}:**"
    out: list[str] = []
    capturing = False
    for line in lines:
        if line.startswith(prefix):
            first = line[len(prefix) :].strip()
            if first:
                out.append(first)
            capturing = True
            continue
        if capturing:
            if line.startswith("- **"):
                break
            if line.strip():
                out.append(line.strip())
    return "\n".join(out).strip()


def split_items(text: str) -> list[tuple[str, str, str]]:
    matches = list(HEADING_RE.finditer(text))
    items: list[tuple[str, str, str]] = []
    for i, match in enumerate(matches):
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        items.append((match.group(1), match.group(2).strip(), text[start:end].strip()))
    return items


def parse_cants(path: Path) -> list[dict]:
    text = path.read_text()
    out = []
    for item_id, title, body in split_items(text):
        lines = body.splitlines()
        out.append(
            {
                "id": item_id,
                "title": title,
                "rightNowICant": field_line(lines, "Right now I can't"),
                "surfaceIds": parse_surface_ids(field_line(lines, "SurfaceIds")),
                "gap": field_line(lines, "Gap"),
                "need": field_line(lines, "Need"),
            }
        )
    return out


def parse_furnish(path: Path) -> list[dict]:
    text = path.read_text()
    out = []
    for item_id, title, body in split_items(text):
        lines = body.splitlines()
        out.append(
            {
                "id": item_id,
                "title": title,
                "supportingAffordance": field_line(lines, "Supporting affordance"),
                "surfaceIds": parse_surface_ids(field_line(lines, "SurfaceIds")),
                "implementationProblem": field_line(lines, "implementationProblem"),
                "implementation": field_block(lines, "implementation"),
                "doesNotChangeCoreFunction": field_line(lines, "Does not change Core Function"),
            }
        )
    return out


def emit_cant_array(items: list[dict]) -> str:
    chunks = []
    for item in items:
        surfaces = ", ".join(ts_str(s) for s in item["surfaceIds"])
        chunks.append(
            "  {\n"
            f"    id: {ts_str(item['id'])},\n"
            f"    title: {ts_str(item['title'])},\n"
            f"    rightNowICant: {ts_str(item['rightNowICant'])},\n"
            f"    surfaceIds: [{surfaces}],\n"
            f"    gap: {ts_str(item['gap'])},\n"
            f"    need: {ts_str(item['need'])},\n"
            "  }"
        )
    return "[\n" + ",\n".join(chunks) + "\n]"


def emit_furnish_array(items: list[dict]) -> str:
    chunks = []
    for item in items:
        surfaces = ", ".join(ts_str(s) for s in item["surfaceIds"])
        chunks.append(
            "  {\n"
            f"    id: {ts_str(item['id'])},\n"
            f"    title: {ts_str(item['title'])},\n"
            f"    supportingAffordance: {ts_str(item['supportingAffordance'])},\n"
            f"    surfaceIds: [{surfaces}],\n"
            f"    implementationProblem: {ts_str(item['implementationProblem'])},\n"
            f"    implementation: {ts_str(item['implementation'])},\n"
            f"    doesNotChangeCoreFunction: {ts_str(item['doesNotChangeCoreFunction'])},\n"
            "  }"
        )
    return "[\n" + ",\n".join(chunks) + "\n]"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    subjects_meta = []
    all_cants = []
    all_furnish = []

    for subject_id, label, cant_file, furnish_file in SUBJECTS:
        cants = parse_cants(ENRICH_DIR / cant_file)
        furnish = parse_furnish(FURNISH_DIR / furnish_file)
        if len(cants) != 20 or len(furnish) != 20:
            raise SystemExit(
                f"{subject_id}: expected 20/20, got {len(cants)} cants / {len(furnish)} furnish"
            )
        subjects_meta.append({"id": subject_id, "label": label, "cantCount": 20, "furnishCount": 20})
        for item in cants:
            item["subjectId"] = subject_id
            all_cants.append(item)
        for item in furnish:
            item["subjectId"] = subject_id
            all_furnish.append(item)

    types = '''export type PersonaEnrichmentSubjectId = "consultant" | "operator" | "contact";

export type PersonaCantItem = {
  id: string;
  subjectId: PersonaEnrichmentSubjectId;
  title: string;
  rightNowICant: string;
  surfaceIds: string[];
  gap: string;
  need: string;
};

export type PersonaFurnishItem = {
  id: string;
  subjectId: PersonaEnrichmentSubjectId;
  title: string;
  supportingAffordance: string;
  surfaceIds: string[];
  implementationProblem: string;
  implementation: string;
  doesNotChangeCoreFunction: string;
};

export type PersonaEnrichmentSubject = {
  id: PersonaEnrichmentSubjectId;
  label: string;
  cantCount: number;
  furnishCount: number;
};
'''
    (OUT_DIR / "types.ts").write_text(types)

    # emit with subjectId
    cant_chunks = []
    for item in all_cants:
        surfaces = ", ".join(ts_str(s) for s in item["surfaceIds"])
        cant_chunks.append(
            "  {\n"
            f"    id: {ts_str(item['id'])},\n"
            f"    subjectId: {ts_str(item['subjectId'])},\n"
            f"    title: {ts_str(item['title'])},\n"
            f"    rightNowICant: {ts_str(item['rightNowICant'])},\n"
            f"    surfaceIds: [{surfaces}],\n"
            f"    gap: {ts_str(item['gap'])},\n"
            f"    need: {ts_str(item['need'])},\n"
            "  }"
        )
    furnish_chunks = []
    for item in all_furnish:
        surfaces = ", ".join(ts_str(s) for s in item["surfaceIds"])
        furnish_chunks.append(
            "  {\n"
            f"    id: {ts_str(item['id'])},\n"
            f"    subjectId: {ts_str(item['subjectId'])},\n"
            f"    title: {ts_str(item['title'])},\n"
            f"    supportingAffordance: {ts_str(item['supportingAffordance'])},\n"
            f"    surfaceIds: [{surfaces}],\n"
            f"    implementationProblem: {ts_str(item['implementationProblem'])},\n"
            f"    implementation: {ts_str(item['implementation'])},\n"
            f"    doesNotChangeCoreFunction: {ts_str(item['doesNotChangeCoreFunction'])},\n"
            "  }"
        )

    subjects_ts = ",\n".join(
        "  {\n"
        f"    id: {ts_str(s['id'])},\n"
        f"    label: {ts_str(s['label'])},\n"
        f"    cantCount: {s['cantCount']},\n"
        f"    furnishCount: {s['furnishCount']},\n"
        "  }"
        for s in subjects_meta
    )

    data = (
        f"{GEN}\n"
        'import type { PersonaCantItem, PersonaEnrichmentSubject, PersonaFurnishItem } from "./types";\n\n'
        f"export const PERSONA_ENRICHMENT_SUBJECTS: PersonaEnrichmentSubject[] = [\n{subjects_ts}\n];\n\n"
        f"export const PERSONA_CANT_ITEMS: PersonaCantItem[] = [\n"
        + ",\n".join(cant_chunks)
        + "\n];\n\n"
        f"export const PERSONA_FURNISH_ITEMS: PersonaFurnishItem[] = [\n"
        + ",\n".join(furnish_chunks)
        + "\n];\n\n"
        "export function getPersonaCantItem(id: string): PersonaCantItem | undefined {\n"
        "  return PERSONA_CANT_ITEMS.find((item) => item.id === id);\n"
        "}\n\n"
        "export function getPersonaFurnishItem(id: string): PersonaFurnishItem | undefined {\n"
        "  return PERSONA_FURNISH_ITEMS.find((item) => item.id === id);\n"
        "}\n\n"
        "export function getPersonaCantsForSubject(subjectId: string): PersonaCantItem[] {\n"
        "  return PERSONA_CANT_ITEMS.filter((item) => item.subjectId === subjectId);\n"
        "}\n\n"
        "export function getPersonaFurnishForSubject(subjectId: string): PersonaFurnishItem[] {\n"
        "  return PERSONA_FURNISH_ITEMS.filter((item) => item.subjectId === subjectId);\n"
        "}\n"
    )
    (OUT_DIR / "personaCantsFurnish.ts").write_text(data)

    index = (
        'export type {\n'
        "  PersonaCantItem,\n"
        "  PersonaEnrichmentSubject,\n"
        "  PersonaEnrichmentSubjectId,\n"
        "  PersonaFurnishItem,\n"
        '} from "./types";\n'
        "export {\n"
        "  PERSONA_CANT_ITEMS,\n"
        "  PERSONA_ENRICHMENT_SUBJECTS,\n"
        "  PERSONA_FURNISH_ITEMS,\n"
        "  getPersonaCantItem,\n"
        "  getPersonaCantsForSubject,\n"
        "  getPersonaFurnishForSubject,\n"
        "  getPersonaFurnishItem,\n"
        '} from "./personaCantsFurnish";\n'
    )
    (OUT_DIR / "index.ts").write_text(index)
    print(f"Synced {len(all_cants)} Can'ts · {len(all_furnish)} Furnish → {OUT_DIR}")


if __name__ == "__main__":
    main()
