#!/usr/bin/env python3
"""Parse docs/wiring/paper-trace into Register wiring theory TS modules."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
DOC_DIR = ROOT / "docs" / "wiring" / "paper-trace"
FUNCTION_DIR = DOC_DIR / "function"
OUT_DIR = ROOT / "src" / "app" / "register" / "theory" / "wiring"

TRACE_HEADING_RE = re.compile(r"^### `([^`]+)`\s+\u2014\s+(.+)$", re.MULTILINE)
GEN_COMMENT = "/** Auto-generated by scripts/sync-wiring-paper-from-docs.py - do not edit by hand. */"


def ts_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def strip_ticks(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value.startswith("`") and value.endswith("`"):
        return value[1:-1]
    return value


def strip_bold_label(line: str, label: str) -> str | None:
    prefix = f"**{label}:**"
    if line.startswith(prefix):
        return line[len(prefix) :].strip()
    return None


def section_lines(body: str) -> list[str]:
    return [line.rstrip() for line in body.strip().splitlines()]


def field_after(lines: list[str], label: str) -> str | None:
    for line in lines:
        value = strip_bold_label(line, label)
        if value is not None:
            return value
    return None


def list_after(lines: list[str], label: str, bullet: str) -> list[str]:
    start = None
    for i, line in enumerate(lines):
        if line.strip() == f"**{label}:**":
            start = i + 1
            break
    if start is None:
        return []

    out: list[str] = []
    for line in lines[start:]:
        if line.startswith("**") and line.endswith(":**"):
            break
        if line.startswith("**") and ":**" in line:
            break
        if not line.strip():
            continue
        if bullet == "number":
            match = re.match(r"^\d+\.\s+(.*)$", line)
            if match:
                out.append(match.group(1).strip())
        elif bullet == "dash" and line.startswith("- "):
            out.append(strip_ticks(line[2:].strip()))
    return out


def detect_deferred_or_blocked(title: str, body: str) -> str | None:
    for marker in ("BLOCKED", "DEFERRED"):
        for line in [title, *section_lines(body)]:
            if marker in line:
                return line.strip()
    return None


def split_trace_sections(md: str) -> list[tuple[str, str, str]]:
    matches = list(TRACE_HEADING_RE.finditer(md))
    sections: list[tuple[str, str, str]] = []
    for i, match in enumerate(matches):
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(md)
        sections.append((match.group(1), strip_ticks(match.group(2)), md[start:end]))
    return sections


def parse_function_trace_file(path: Path) -> tuple[dict, list[str]]:
    md = path.read_text(encoding="utf-8")
    failures: list[str] = []
    title = md.splitlines()[0].removeprefix("# ").strip()
    seat = {
        "id": path.stem.lower(),
        "label": title.replace("Function traces - ", "").replace("Function traces \u2014 ", ""),
        "items": [],
    }

    for trace_id, trace_title, body in split_trace_sections(md):
        lines = section_lines(body)
        implementation = field_after(lines, "Implementation (source)") or ""
        start = strip_ticks(field_after(lines, "Start") or "")
        path_hops = list_after(lines, "Path", "number")
        nodes_touched = list_after(lines, "Nodes touched", "dash")
        facets = field_after(lines, "Facets swept") or ""
        missing_seat = field_after(lines, "Missing seat flag (optional)")

        missing = [
            name
            for name, value in [
                ("Implementation (source)", implementation),
                ("Start", start),
                ("Path", path_hops),
                ("Nodes touched", nodes_touched),
                ("Facets swept", facets),
            ]
            if not value
        ]
        if missing:
            failures.append(f"{path.name}:{trace_id} missing {', '.join(missing)}")

        item = {
            "id": trace_id,
            "title": trace_title,
            "implementationSource": implementation,
            "start": start,
            "pathHops": path_hops,
            "nodesTouched": nodes_touched,
            "facets": facets,
        }
        if missing_seat:
            item["missingSeatFlag"] = missing_seat
        deferred_or_blocked = detect_deferred_or_blocked(trace_title, body)
        if deferred_or_blocked:
            item["deferredOrBlocked"] = deferred_or_blocked
        seat["items"].append(item)

    expected_line = next((line for line in md.splitlines() if line.startswith("**Items:**")), None)
    if expected_line:
        expected = int(expected_line.split(":", 1)[1].strip().strip("*").strip())
        if expected != len(seat["items"]):
            failures.append(f"{path.name}: expected {expected} trace sections, parsed {len(seat['items'])}")

    return seat, failures


def split_table_row(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def parse_canonical_nodes(path: Path) -> list[dict]:
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| `"):
            continue
        cells = split_table_row(line)
        if len(cells) != 6:
            raise ValueError(f"{path.name}: malformed table row: {line}")
        rows.append(
            {
                "node": strip_ticks(cells[0]),
                "definition": cells[1],
                "altitude": cells[2],
                "seats": [seat.strip() for seat in cells[3].split(",")],
                "existenceBucket": cells[4],
                "humanProvisioningDependency": "" if cells[5] == "\u2014" else cells[5],
            }
        )
    return rows


def split_named_sections(md: str, prefix: str) -> list[tuple[str, str, str]]:
    pattern = re.compile(rf"^### `({re.escape(prefix)}-\d+)`\s+\u2014\s+(.+)$", re.MULTILINE)
    matches = list(pattern.finditer(md))
    sections: list[tuple[str, str, str]] = []
    for i, match in enumerate(matches):
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(md)
        sections.append((match.group(1), strip_ticks(match.group(2)), md[start:end]))
    return sections


def bullet_fields(body: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in section_lines(body):
        match = re.match(r"^-\s+\*\*([^:]+):\*\*\s+(.*)$", line)
        if match:
            fields[match.group(1)] = match.group(2).strip()
    return fields


def split_inline_nodes(value: str) -> list[str]:
    ticked = re.findall(r"`([^`]+)`", value)
    if ticked:
        return ticked
    return [part.strip() for part in value.split(",") if part.strip()]


def parse_cants_and_furnish(path: Path) -> tuple[list[dict], list[dict], list[str]]:
    md = path.read_text(encoding="utf-8")
    failures: list[str] = []
    cants: list[dict] = []
    furnish: list[dict] = []

    for item_id, title, body in split_named_sections(md, "cant"):
        fields = bullet_fields(body)
        required = ["Failure mode", "Where it hangs", "Guard to add", "Seats implicated"]
        missing = [field for field in required if field not in fields]
        if missing:
            failures.append(f"{path.name}:{item_id} missing {', '.join(missing)}")
        cants.append(
            {
                "id": item_id,
                "title": title,
                "failureMode": fields.get("Failure mode", ""),
                "whereItHangs": [part.strip() for part in fields.get("Where it hangs", "").split(";") if part.strip()],
                "guardToAdd": fields.get("Guard to add", ""),
                "seats": [seat.strip() for seat in fields.get("Seats implicated", "").split(",") if seat.strip()],
            }
        )

    for item_id, title, body in split_named_sections(md, "furnish"):
        fields = bullet_fields(body)
        required = ["Ops node", "Purpose", "Attaches to Function nodes", "Does not change Function"]
        missing = [field for field in required if field not in fields]
        if missing:
            failures.append(f"{path.name}:{item_id} missing {', '.join(missing)}")
        furnish.append(
            {
                "id": item_id,
                "title": title,
                "opsNode": strip_ticks(fields.get("Ops node", "")),
                "purpose": fields.get("Purpose", ""),
                "attachesToFunctionNodes": split_inline_nodes(fields.get("Attaches to Function nodes", "")),
                "doesNotChangeFunction": fields.get("Does not change Function", ""),
            }
        )

    return cants, furnish, failures


def parse_human_provisioning(path: Path) -> tuple[list[dict], list[str]]:
    md = path.read_text(encoding="utf-8")
    failures: list[str] = []
    nodes: list[dict] = []
    pattern = re.compile(r"^### `([^`]+)`\s*$", re.MULTILINE)
    matches = list(pattern.finditer(md))
    sections: list[tuple[str, str]] = []
    for i, match in enumerate(matches):
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(md)
        sections.append((match.group(1), md[start:end]))

    for node, body in sections:
        fields = bullet_fields(body)
        required = ["Requires to exist", "Scope", "Inherited by", "Related Function seats"]
        missing = [field for field in required if field not in fields]
        if missing:
            failures.append(f"{path.name}:{node} missing {', '.join(missing)}")
        nodes.append(
            {
                "node": node,
                "requiresToExist": fields.get("Requires to exist", ""),
                "scope": fields.get("Scope", ""),
                "inheritedBy": fields.get("Inherited by", ""),
                "relatedFunctionSeats": [
                    seat.strip() for seat in fields.get("Related Function seats", "").split(",") if seat.strip()
                ],
            }
        )
    return nodes, failures


def emit_object(value: object, indent: int = 0) -> str:
    pad = " " * indent
    if isinstance(value, str):
        return ts_str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        if all(isinstance(item, str) for item in value):
            return "[" + ", ".join(ts_str(item) for item in value) + "]"
        inner = ",\n".join(emit_object(item, indent + 2) for item in value)
        return "[\n" + inner + "\n" + pad + "]"
    if isinstance(value, dict):
        lines = ["{"]
        for key, item in value.items():
            if item == "" and key == "humanProvisioningDependency":
                lines.append(f"{' ' * (indent + 2)}{key}: null,")
            else:
                lines.append(f"{' ' * (indent + 2)}{key}: {emit_object(item, indent + 2)},")
        lines.append(pad + "}")
        return "\n".join(lines)
    if value is None:
        return "null"
    raise TypeError(f"Unsupported emit value: {type(value)}")


def emit_array_module(
    imports: Iterable[str],
    const_name: str,
    type_name: str,
    data: list[dict],
    helpers: Iterable[str],
) -> str:
    lines = [*imports, "", GEN_COMMENT, f"export const {const_name}: {type_name}[] = "]
    lines[-1] += emit_object(data, 0) + ";"
    lines.extend(["", *helpers, ""])
    return "\n".join(lines)


def write_types() -> None:
    content = """export type WiringTraceItem = {
  id: string;
  title: string;
  implementationSource: string;
  start: string;
  pathHops: string[];
  nodesTouched: string[];
  facets: string;
  missingSeatFlag?: string;
  deferredOrBlocked?: string;
};

export type WiringSeatTraces = {
  id: string;
  label: string;
  items: WiringTraceItem[];
};

export type CanonicalNode = {
  node: string;
  definition: string;
  altitude: string;
  seats: string[];
  existenceBucket: string;
  humanProvisioningDependency: string | null;
};

export type CantItem = {
  id: string;
  title: string;
  failureMode: string;
  whereItHangs: string[];
  guardToAdd: string;
  seats: string[];
};

export type FurnishItem = {
  id: string;
  title: string;
  opsNode: string;
  purpose: string;
  attachesToFunctionNodes: string[];
  doesNotChangeFunction: string;
};

export type HumanProvisioningNode = {
  node: string;
  requiresToExist: string;
  scope: string;
  inheritedBy: string;
  relatedFunctionSeats: string[];
};
"""
    (OUT_DIR / "types.ts").write_text(content, encoding="utf-8")


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "function").mkdir(parents=True, exist_ok=True)
    failures: list[str] = []

    function_seats: list[dict] = []
    for path in sorted(FUNCTION_DIR.glob("C*.md")):
        seat, seat_failures = parse_function_trace_file(path)
        function_seats.append(seat)
        failures.extend(seat_failures)

    canonical_nodes = parse_canonical_nodes(DOC_DIR / "CANONICAL-NODES.md")
    cants, furnish, cf_failures = parse_cants_and_furnish(DOC_DIR / "CANTS-AND-FURNISH.md")
    human_nodes, human_failures = parse_human_provisioning(DOC_DIR / "HUMAN-PROVISIONING-SET.md")
    failures.extend(cf_failures)
    failures.extend(human_failures)

    write_types()
    (OUT_DIR / "function" / "index.ts").write_text(
        emit_array_module(
            ['import type { WiringSeatTraces } from "../types";'],
            "WIRING_FUNCTION_TRACES",
            "WiringSeatTraces",
            function_seats,
            [
                "export function getWiringSeatTraces(seatId: string): WiringSeatTraces | undefined {",
                "  return WIRING_FUNCTION_TRACES.find((seat) => seat.id === seatId);",
                "}",
                "",
                "export function getWiringTraceItem(seatId: string, traceId: string) {",
                "  return getWiringSeatTraces(seatId)?.items.find((item) => item.id === traceId);",
                "}",
            ],
        ),
        encoding="utf-8",
    )
    (OUT_DIR / "canonicalNodes.ts").write_text(
        emit_array_module(
            ['import type { CanonicalNode } from "./types";'],
            "CANONICAL_NODES",
            "CanonicalNode",
            canonical_nodes,
            [
                "export function getCanonicalNode(nodeName: string): CanonicalNode | undefined {",
                "  return CANONICAL_NODES.find((node) => node.node === nodeName);",
                "}",
            ],
        ),
        encoding="utf-8",
    )
    (OUT_DIR / "cantsAndFurnish.ts").write_text(
        "\n".join(
            [
                'import type { CantItem, FurnishItem } from "./types";',
                "",
                GEN_COMMENT,
                f"export const CANT_ITEMS: CantItem[] = {emit_object(cants, 0)};",
                "",
                f"export const FURNISH_ITEMS: FurnishItem[] = {emit_object(furnish, 0)};",
                "",
                "export function getCantItem(cantId: string): CantItem | undefined {",
                "  return CANT_ITEMS.find((item) => item.id === cantId);",
                "}",
                "",
                "export function getFurnishItem(furnishId: string): FurnishItem | undefined {",
                "  return FURNISH_ITEMS.find((item) => item.id === furnishId);",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    (OUT_DIR / "humanProvisioning.ts").write_text(
        emit_array_module(
            ['import type { HumanProvisioningNode } from "./types";'],
            "HUMAN_PROVISIONING_NODES",
            "HumanProvisioningNode",
            human_nodes,
            [
                "export function getHumanProvisioningNode(nodeName: string): HumanProvisioningNode | undefined {",
                "  return HUMAN_PROVISIONING_NODES.find((node) => node.node === nodeName);",
                "}",
            ],
        ),
        encoding="utf-8",
    )
    (OUT_DIR / "index.ts").write_text(
        "\n".join(
            [
                'export type {',
                "  WiringTraceItem,",
                "  WiringSeatTraces,",
                "  CantItem,",
                "  FurnishItem,",
                "  CanonicalNode,",
                "  HumanProvisioningNode,",
                '} from "./types";',
                'export { WIRING_FUNCTION_TRACES, getWiringSeatTraces, getWiringTraceItem } from "./function";',
                'export { CANONICAL_NODES, getCanonicalNode } from "./canonicalNodes";',
                'export { CANT_ITEMS, FURNISH_ITEMS, getCantItem, getFurnishItem } from "./cantsAndFurnish";',
                'export { HUMAN_PROVISIONING_NODES, getHumanProvisioningNode } from "./humanProvisioning";',
                "",
            ]
        ),
        encoding="utf-8",
    )

    print("Wiring paper sync complete")
    total = 0
    for seat in function_seats:
        total += len(seat["items"])
        print(f"  {seat['id']}: {len(seat['items'])} traces")
    print(f"  canonicalNodes: {len(canonical_nodes)}")
    print(f"  cants: {len(cants)}")
    print(f"  furnish: {len(furnish)}")
    print(f"  humanProvisioning: {len(human_nodes)}")
    print(f"TOTAL function traces: {total}")
    if failures:
        print("Parse failures:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("Parse failures: 0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
