import type { PriorEntry } from "./types";

/** Desk→lattice census — Agents / Audits / Activity. Purposes empty. */
export const AGENTS_PRIORS: PriorEntry[] = [
  {
    id: "ag-nav-libraries-agents",
    module: "Agents",
    title: "Libraries nav → Agents",
    where: "plant+Ant Config libraries aside",
    kind: "nav",
    mark: "latticed",
    latticeHint: "How operator-configuration-libraries leaf 1.3 Engagement templates",
    notes: "Plant/Ant label Agents; How names Engagement templates",
    purposes: [],
  },
  {
    id: "ag-catalog-row",
    module: "Agents",
    title: "Select agent / template catalog row",
    where: "plant+Ant Engagement templates catalog",
    kind: "open",
    mark: "latticed",
    latticeHint: "How leaf 1.3 — click template row",
    notes: "Opens Agent / sequence editor",
    purposes: [],
  },
  {
    id: "ag-new-template",
    module: "Agents",
    title: "New template",
    where: "plant+Ant catalog actions",
    kind: "commit",
    mark: "latticed",
    latticeHint: "How leaf 1.3 New template",
    notes: "Creates draft row; omitted from Bind until publish",
    purposes: [],
  },
  {
    id: "ag-publish-version",
    module: "Agents",
    title: "Publish version",
    where: "plant Config libraries editor chrome (Agents sub)",
    kind: "commit",
    mark: "latticed",
    latticeHint: "How leaf 1.3 Publish version; Furnish Published/Draft",
    notes: "Ant Agents workbench uses shared Config libraries publish chrome when present",
    purposes: [],
  },
  {
    id: "ag-compare-versions",
    module: "Agents",
    title: "Compare versions",
    where: "plant+Ant Config libraries (Agents sub)",
    kind: "open",
    mark: "latticed",
    latticeHint: "Enrichment op-cant-18 Compare versions Need",
    notes: "View-only; does not Bind",
    purposes: [],
  },
  {
    id: "ag-tab-editor",
    module: "Agents",
    title: "Editor tab",
    where: "plant AgentEditor + Ant workbench Tabs",
    kind: "tab",
    mark: "latticed",
    latticeHint: "How Agent / sequence editor; C2 SME step-rail authorship",
    notes: "Default authorship surface",
    purposes: [],
  },
  {
    id: "ag-tab-contacts",
    module: "Agents",
    title: "Contacts tab",
    where: "plant+Ant agent tabs",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "Empty placeholder copy only",
    purposes: [],
  },
  {
    id: "ag-tab-activity",
    module: "Agents",
    title: "Activity tab (agent-local)",
    where: "plant+Ant agent tabs",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "Empty placeholder — not consultant Engagement record",
    purposes: [],
  },
  {
    id: "ag-tab-report",
    module: "Agents",
    title: "Report tab",
    where: "plant+Ant agent tabs",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "Empty placeholder",
    purposes: [],
  },
  {
    id: "ag-tab-settings",
    module: "Agents",
    title: "Settings tab",
    where: "plant+Ant agent tabs",
    kind: "tab",
    mark: "weak",
    latticeHint: "C2 channel rulesets on step rail; How does not name Settings tab",
    notes: "Empty placeholder; authorship named on step rail instead",
    purposes: [],
  },
  {
    id: "ag-launch-agent",
    module: "Agents",
    title: "Launch agent",
    where: "plant AgentHeader + Ant header",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Soft commit stub; no lattice statement",
    purposes: [],
  },
  {
    id: "ag-more-actions",
    module: "Agents",
    title: "More actions menu",
    where: "plant AgentHeader ⋯",
    kind: "menu",
    mark: "prior",
    latticeHint: "",
    notes: "Opens dropdown",
    purposes: [],
  },
  {
    id: "ag-add-contacts",
    module: "Agents",
    title: "Add contacts",
    where: "plant More actions item",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Stub menu item",
    purposes: [],
  },
  {
    id: "ag-linked-automations",
    module: "Agents",
    title: "Linked automations peek",
    where: "plant AgentHeader Zap control",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "HoverCard list; Ant shows count Tag only",
    purposes: [],
  },
  {
    id: "ag-toggle-step-rail",
    module: "Agents",
    title: "Collapse / expand step rail",
    where: "plant step toolbar",
    kind: "toggle",
    mark: "weak",
    latticeHint: "How / C2 name step rail as authorship surface",
    notes: "Control itself unnamed",
    purposes: [],
  },
  {
    id: "ag-save-changes",
    module: "Agents",
    title: "Save changes",
    where: "plant step toolbar",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Stub; lattice commit is Publish version",
    purposes: [],
  },
  {
    id: "ag-add-step",
    module: "Agents",
    title: "Add a step",
    where: "plant empty state + canvas insert + Ant step toolbar",
    kind: "commit",
    mark: "weak",
    latticeHint: "How edit ordered channel + copy steps; C2 step rail",
    notes: "Menu/control label not in How",
    purposes: [],
  },
  {
    id: "ag-add-step-email",
    module: "Agents",
    title: "Add step → Email",
    where: "plant Add-step menu + Ant toolbar",
    kind: "commit",
    mark: "weak",
    latticeHint: "How ordered channel steps; C2 email/send steps",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-add-step-task",
    module: "Agents",
    title: "Add step → Consultant task",
    where: "plant Add-step menu + Ant toolbar",
    kind: "commit",
    mark: "weak",
    latticeHint: "How / C2 consultant-task steps",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-empty-select-template",
    module: "Agents",
    title: "Select a template (empty state)",
    where: "plant AgentEditorEmptyState",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Placeholder beside Add a step",
    purposes: [],
  },
  {
    id: "ag-empty-ai-assisted",
    module: "Agents",
    title: "AI-assisted agent (empty state)",
    where: "plant AgentEditorEmptyState",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Placeholder",
    purposes: [],
  },
  {
    id: "ag-select-step",
    module: "Agents",
    title: "Select step on canvas / rail",
    where: "plant sequence canvas + step rail",
    kind: "open",
    mark: "weak",
    latticeHint: "How Step rail / Sequence canvas",
    notes: "Selection chrome unnamed",
    purposes: [],
  },
  {
    id: "ag-collapse-step",
    module: "Agents",
    title: "Collapse / expand step",
    where: "plant step frame + rail",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-more-step-actions",
    module: "Agents",
    title: "More step actions",
    where: "plant step frame ⋯",
    kind: "menu",
    mark: "prior",
    latticeHint: "",
    notes: "No menu items wired",
    purposes: [],
  },
  {
    id: "ag-reorder-step",
    module: "Agents",
    title: "Move step up / down",
    where: "Ant StepCard arrows",
    kind: "reorder",
    mark: "prior",
    latticeHint: "",
    notes: "Plant has no reorder control; order implied by insert",
    purposes: [],
  },
  {
    id: "ag-email-compose-tabs",
    module: "Agents",
    title: "Email Assisted / Prompt / Template tabs",
    where: "plant EmailStepNode",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "Template styled active; others inert",
    purposes: [],
  },
  {
    id: "ag-email-thread-type",
    module: "Agents",
    title: "Email thread type (New / Reply)",
    where: "plant EmailStepNode select",
    kind: "select",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-email-preview-refresh",
    module: "Agents",
    title: "Refresh preview",
    where: "plant EmailStepNode",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-email-preview-desktop",
    module: "Agents",
    title: "Desktop preview",
    where: "plant EmailStepNode",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-email-preview-mobile",
    module: "Agents",
    title: "Mobile preview",
    where: "plant EmailStepNode",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-email-preview-options",
    module: "Agents",
    title: "Preview options",
    where: "plant EmailStepNode",
    kind: "menu",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-task-priority",
    module: "Agents",
    title: "Task priority select",
    where: "plant TaskStepNode",
    kind: "select",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ag-task-skip-after",
    module: "Agents",
    title: "Skip after days checkbox + days",
    where: "plant TaskStepNode",
    kind: "checkbox",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
];

export const AUDITS_PRIORS: PriorEntry[] = [
  {
    id: "au-select-audit",
    module: "Audits",
    title: "Select Audits catalog row",
    where: "plant+Ant Audits aside list",
    kind: "open",
    mark: "latticed",
    latticeHint: "How operator-book-readiness — click Audits / open Audit run",
    notes: "Opens Audit run detail",
    purposes: [],
  },
  {
    id: "au-checkboxes",
    module: "Audits",
    title: "Audit services / check checkboxes",
    where: "plant AuditServicesPanel + Ant Services/checks",
    kind: "checkbox",
    mark: "latticed",
    latticeHint: "How leaf 1.1 check email/phone/channel/dedupe/consent/name",
    notes: "Plant also has Run-checks select-all",
    purposes: [],
  },
  {
    id: "au-verdict-filter",
    module: "Audits",
    title: "Verdict filter",
    where: "Ant Book readiness Select (All/Pass/Fail/Pending)",
    kind: "select",
    mark: "latticed",
    latticeHint: "Enrichment op-cant-06 Verdict filter Need",
    notes: "Ant only — plant list has no filter",
    purposes: [],
  },
  {
    id: "au-re-audit-remainder",
    module: "Audits",
    title: "Re-audit remainder",
    where: "Ant Book readiness button",
    kind: "commit",
    mark: "latticed",
    latticeHint: "Enrichment op-cant-06 Re-audit remainder Need",
    notes: "Ant only — plant missing",
    purposes: [],
  },
  {
    id: "au-sort-records",
    module: "Audits",
    title: "Sort records",
    where: "plant AuditRecordsTable + Ant Records toolbar",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Plant icon stub; Ant toggles name asc/desc",
    purposes: [],
  },
  {
    id: "au-inspect-record",
    module: "Audits",
    title: "Inspect record",
    where: "plant toolbar + Ant eye / row click",
    kind: "inspect",
    mark: "prior",
    latticeHint: "",
    notes: "No lattice inspect affordance; How only view verdict chips",
    purposes: [],
  },
  {
    id: "au-export-download-records",
    module: "Audits",
    title: "Export / Download records CSV",
    where: "plant Export + Ant Download CSV",
    kind: "download",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "au-select-record-row",
    module: "Audits",
    title: "Select / highlight record row",
    where: "Ant Records table onRow",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Sets inspected highlight",
    purposes: [],
  },
];

export const ACTIVITY_PRIORS: PriorEntry[] = [
  {
    id: "ac-tab-engagement",
    module: "Activity",
    title: "Engagement record tab",
    where: "plant+Ant Client workspace tabs",
    kind: "tab",
    mark: "latticed",
    latticeHint: "How consultant-governance leaf 1.1 Engagement record (Activity)",
    notes: "Opens chronology surface",
    purposes: [],
  },
  {
    id: "ac-halt-outreach",
    module: "Activity",
    title: "Halt outreach",
    where: "plant+Ant Engagement record / workspace chrome",
    kind: "commit",
    mark: "latticed",
    latticeHint: "How governance leaf 1.2 Halt outreach",
    notes: "Also on Board; included because mounted on Activity seat",
    purposes: [],
  },
  {
    id: "ac-lift-halt",
    module: "Activity",
    title: "Lift halt",
    where: "plant+Ant when halted",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Inverse of Halt; not named in How",
    purposes: [],
  },
  {
    id: "ac-export-chronology",
    module: "Activity",
    title: "Export chronology",
    where: "Ant Engagement record actions",
    kind: "download",
    mark: "latticed",
    latticeHint: "Furnish cons-furnish-20 Export chronology",
    notes: "Ant only — plant missing",
    purposes: [],
  },
  {
    id: "ac-tree-expand",
    module: "Activity",
    title: "Expand / collapse engagement tree nodes",
    where: "plant JourneyTab headers + Ant Tree onExpand",
    kind: "toggle",
    mark: "weak",
    latticeHint: "How chronology rows (view)",
    notes: "Tree chrome unnamed",
    purposes: [],
  },
  {
    id: "ac-tree-select",
    module: "Activity",
    title: "Select chronology / tree node",
    where: "plant touchpoint select + Ant Tree onSelect",
    kind: "open",
    mark: "weak",
    latticeHint: "How / C2 Engagement record chronology",
    notes: "Selection → highlight / inspector",
    purposes: [],
  },
  {
    id: "ac-show-reasoning",
    module: "Activity",
    title: "Show / Hide reasoning",
    where: "plant JourneyTab ReasoningToggle",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ac-node-inspect",
    module: "Activity",
    title: "Open node inspector",
    where: "plant JourneyTab channel/form inspect",
    kind: "inspect",
    mark: "weak",
    latticeHint: "C2 chronology stays inspectable; no named inspector control",
    notes: "Opens EngagementNodePanel",
    purposes: [],
  },
  {
    id: "ac-inspector-tabs",
    module: "Activity",
    title: "Node inspector Overview / Metadata tabs",
    where: "plant EngagementNodePanel",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ac-inspector-close",
    module: "Activity",
    title: "Close node inspector",
    where: "plant EngagementNodePanel",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ac-zoom-in",
    module: "Activity",
    title: "Zoom in (day axis)",
    where: "plant JourneyTab + Ant ActivityTimeline",
    kind: "zoom",
    mark: "prior",
    latticeHint: "",
    notes: "Product gantt log only — outside lattice refs",
    purposes: [],
  },
  {
    id: "ac-zoom-out",
    module: "Activity",
    title: "Zoom out (day axis)",
    where: "plant JourneyTab + Ant ActivityTimeline",
    kind: "zoom",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ac-scroll-today",
    module: "Activity",
    title: "Scroll to today / Today",
    where: "plant JourneyTab Today button",
    kind: "scroll",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "ac-pane-resize",
    module: "Activity",
    title: "Pane resize (list ↔ timeline)",
    where: "plant JourneyTab drag handle + Ant Splitter",
    kind: "resize",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
  {
    id: "ac-gantt-segment",
    module: "Activity",
    title: "Timeline segment / marker click",
    where: "plant NudgeGantt interactive segments",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Ant timeline bars are title-tooltips only (non-click)",
    purposes: [],
  },
  {
    id: "ac-reveal-thought",
    module: "Activity",
    title: "Reveal escalation thought",
    where: "plant nudge escalation row",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "",
    purposes: [],
  },
];

export const AGENTS_AUDITS_ACTIVITY_PRIORS: PriorEntry[] = [
  ...AGENTS_PRIORS,
  ...AUDITS_PRIORS,
  ...ACTIVITY_PRIORS,
];
