import type { PriorEntry } from "./types";

/** Desk→lattice census — Automations. Purposes empty. Kinds normalized to PriorKind. */
export const AUTOMATIONS_PRIORS: PriorEntry[] = [
  {
    id: "auto-nav-automations",
    module: "Automations",
    title: "Libraries nav → Automations",
    where: "Configuration libraries / Libraries nav",
    kind: "nav",
    mark: "latticed",
    latticeHint: "how/operator-configuration-libraries.md · Leaf 1.2",
    notes: "Plant navLabel Automations; Ant Menu Automation workflows",
    purposes: [],
  },
  {
    id: "auto-catalog-row",
    module: "Automations",
    title: "Open workflow catalog row",
    where: "Automations / catalog",
    kind: "open",
    mark: "latticed",
    latticeHint: "how · Leaf 1.2",
    notes: "Ant selects real workflow; plant pack row does not swap DEMO id",
    purposes: [],
  },
  {
    id: "auto-new-workflow",
    module: "Automations",
    title: "New workflow",
    where: "Automations / catalog",
    kind: "commit",
    mark: "latticed",
    latticeHint: "how · Leaf 1.2",
    notes: "Ant createAutomation(); plant seeds Draft pack",
    purposes: [],
  },
  {
    id: "auto-compare-versions",
    module: "Automations",
    title: "Compare versions",
    where: "Automations / catalog chrome",
    kind: "commit",
    mark: "latticed",
    latticeHint: "enrichment · op-cant-18",
    notes: "Densify fill of Can't",
    purposes: [],
  },
  {
    id: "auto-publish-version",
    module: "Automations",
    title: "Publish version",
    where: "Automations / editor chrome",
    kind: "commit",
    mark: "latticed",
    latticeHint: "how · Leaf 1.2",
    notes: "Ant top chrome; plant canvas footer",
    purposes: [],
  },
  {
    id: "auto-compare-version-a",
    module: "Automations",
    title: "Compare · Version A",
    where: "Compare versions modal",
    kind: "select",
    mark: "weak",
    latticeHint: "under op-cant-18",
    notes: "View-only picker",
    purposes: [],
  },
  {
    id: "auto-compare-version-b",
    module: "Automations",
    title: "Compare · Version B",
    where: "Compare versions modal",
    kind: "select",
    mark: "weak",
    latticeHint: "under op-cant-18",
    notes: "View-only picker",
    purposes: [],
  },
  {
    id: "auto-compare-close",
    module: "Automations",
    title: "Close compare",
    where: "Compare versions modal",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Dismiss only",
    purposes: [],
  },
  {
    id: "auto-rename",
    module: "Automations",
    title: "Rename automation",
    where: "Workflow detail / header",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Both eras",
    purposes: [],
  },
  {
    id: "auto-share",
    module: "Automations",
    title: "Share workflow",
    where: "Workflow detail / header",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only; unwired chrome",
    purposes: [],
  },
  {
    id: "auto-save",
    module: "Automations",
    title: "Save",
    where: "Workflow detail / header",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Both eras",
    purposes: [],
  },
  {
    id: "auto-launch",
    module: "Automations",
    title: "Launch workflow / Stop run",
    where: "Workflow detail / header",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Ant toggles Stop; plant Launch stubbed",
    purposes: [],
  },
  {
    id: "auto-tab-workflow",
    module: "Automations",
    title: "Workflow tab",
    where: "Editor tabs",
    kind: "tab",
    mark: "weak",
    latticeHint: "how · Leaf 1.2 Workflow canvas",
    notes: "Tab itself unnamed",
    purposes: [],
  },
  {
    id: "auto-tab-runs",
    module: "Automations",
    title: "Runs tab",
    where: "Editor tabs",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "Rows display-only",
    purposes: [],
  },
  {
    id: "auto-tab-settings",
    module: "Automations",
    title: "Settings tab",
    where: "Editor tabs",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "Empty placeholder",
    purposes: [],
  },
  {
    id: "auto-tab-enrollment",
    module: "Automations",
    title: "Enrollment tab",
    where: "Editor tabs",
    kind: "tab",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only; Ant omits",
    purposes: [],
  },
  {
    id: "auto-build-toggle",
    module: "Automations",
    title: "Show / hide Build panel",
    where: "Editor tabs chrome",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-empty-add-trigger",
    module: "Automations",
    title: "Empty canvas · Add trigger",
    where: "Workflow canvas / empty state",
    kind: "menu",
    mark: "weak",
    latticeHint: "how Trigger nodes; SME C1/C2",
    notes: "Plant empty-state menu",
    purposes: [],
  },
  {
    id: "auto-palette-add-trigger",
    module: "Automations",
    title: "Build palette · Add trigger",
    where: "Build palette",
    kind: "commit",
    mark: "weak",
    latticeHint: "how · Trigger nodes",
    notes: "Event/schedule/manual/constant",
    purposes: [],
  },
  {
    id: "auto-palette-add-block",
    module: "Automations",
    title: "Build palette · Add block",
    where: "Build palette",
    kind: "commit",
    mark: "weak",
    latticeHint: "how nodes; SME C1/C2 enroll action",
    notes: "Constant/branch/rule/action/exit",
    purposes: [],
  },
  {
    id: "auto-node-open",
    module: "Automations",
    title: "Open / select canvas node",
    where: "Workflow canvas",
    kind: "open",
    mark: "weak",
    latticeHint: "how · nodes + canvas",
    notes: "Ant opens Drawer",
    purposes: [],
  },
  {
    id: "auto-node-configure",
    module: "Automations",
    title: "Configure node",
    where: "Canvas node",
    kind: "commit",
    mark: "weak",
    latticeHint: "how · edit trigger→rules→actions",
    notes: "Plant modal; Ant Drawer",
    purposes: [],
  },
  {
    id: "auto-node-manual-run",
    module: "Automations",
    title: "Run / Stop manual trigger (node)",
    where: "Trigger node",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-enrollment-open",
    module: "Automations",
    title: "Open enrollment criteria",
    where: "Trigger · Enrollment criteria",
    kind: "open",
    mark: "weak",
    latticeHint: "how enroll; SME C1/C2",
    notes: "Plant manual-trigger card",
    purposes: [],
  },
  {
    id: "auto-enrollment-filter",
    module: "Automations",
    title: "Edit class filter",
    where: "Enrollment criteria · class row",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Plant pencil",
    purposes: [],
  },
  {
    id: "auto-class-filter-done",
    module: "Automations",
    title: "Done (class filter)",
    where: "Filter configuration panel",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-toolbar-attach",
    module: "Automations",
    title: "Add connected step",
    where: "Node toolbar",
    kind: "menu",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-toolbar-duplicate",
    module: "Automations",
    title: "Duplicate node",
    where: "Node toolbar",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-toolbar-delete",
    module: "Automations",
    title: "Delete node",
    where: "Node toolbar",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-edge-insert",
    module: "Automations",
    title: "Insert step on edge",
    where: "Canvas edge",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Plant +",
    purposes: [],
  },
  {
    id: "auto-attach-pick-block",
    module: "Automations",
    title: "Attach / insert menu · pick block",
    where: "Attach / Edge insert menu",
    kind: "menu",
    mark: "prior",
    latticeHint: "",
    notes: "Plant; distinct from palette",
    purposes: [],
  },
  {
    id: "auto-attach-branch-handle",
    module: "Automations",
    title: "Branch handle true / false",
    where: "Attach step menu",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Plant If-node attach",
    purposes: [],
  },
  {
    id: "auto-attach-close",
    module: "Automations",
    title: "Close attach / insert menu",
    where: "Attach / Edge insert menu",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-config-run",
    module: "Automations",
    title: "Run node",
    where: "Node config modal",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Plant manual/If/Rule",
    purposes: [],
  },
  {
    id: "auto-config-close",
    module: "Automations",
    title: "Close node config",
    where: "Config modal / Ant Drawer",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Both eras",
    purposes: [],
  },
  {
    id: "auto-config-view-code",
    module: "Automations",
    title: "View code / Hide code",
    where: "Config · Rule outcomes",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "auto-canvas-controls",
    module: "Automations",
    title: "Canvas zoom / fit controls",
    where: "Workflow canvas",
    kind: "zoom",
    mark: "prior",
    latticeHint: "",
    notes: "ReactFlow Controls; Ant MiniMap",
    purposes: [],
  },
  {
    id: "auto-ant-palette-collapse",
    module: "Automations",
    title: "Build palette section collapse",
    where: "Ant Build aside",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Ant Collapse only",
    purposes: [],
  },
];
