import type { PriorEntry } from "./types";

/** Desk→lattice census — Board / Contacts / Meetings / Prepared / Login / Contact / Operator leftovers / Global CT. Purposes empty. */
export const BOARD_PRIORS: PriorEntry[] = [
  {
    id: "board-view-as-client",
    module: "Board",
    title: "View as Client",
    where: "plant BoardPanel row ⋯ menu (sarah)",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "onViewAsClient unwired in CT scene — no-op",
    purposes: [],
  },
  {
    id: "board-row-actions-menu",
    module: "Board",
    title: "Client actions ⋯",
    where: "plant BoardPanel row menu",
    kind: "menu",
    mark: "prior",
    latticeHint: "",
    notes: "Chrome that hosts Halt / View as Client",
    purposes: [],
  },
  {
    id: "board-resume-book",
    module: "Board",
    title: "Resume book",
    where: "plant+Ant Board when firm book halted",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Inverse of Halt firm book; not named",
    purposes: [],
  },
  {
    id: "board-resume-outreach",
    module: "Board",
    title: "Resume outreach",
    where: "plant BoardPanel row menu when contact halted",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Inverse of Halt outreach",
    purposes: [],
  },
  {
    id: "board-lift-halt",
    module: "Board",
    title: "Lift halt",
    where: "plant+Ant Client workspace when halted",
    kind: "commit",
    mark: "prior",
    latticeHint: "",
    notes: "Keep prior per Activity census; Enrichment cons-cant-04 names Need not How/Furnish control",
    purposes: [],
  },
  {
    id: "board-newest-first",
    module: "Board",
    title: "Newest first / Oldest first",
    where: "Ant BoardModule Segmented",
    kind: "toggle",
    mark: "weak",
    latticeHint: "Furnish cons-furnish-06 Newest first on Engagement record",
    notes: "Mis-seated on Board list sort",
    purposes: [],
  },
  {
    id: "board-halt-modal-dismiss",
    module: "Board",
    title: "Halt outreach dismiss (backdrop / Cancel)",
    where: "plant+Ant Halt modal",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Modal dismiss unnamed",
    purposes: [],
  },
];

export const CONTACTS_PRIORS: PriorEntry[] = [
  {
    id: "contacts-search",
    module: "Contacts",
    title: "Search contacts",
    where: "Ant ContactsModule Input.Search",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Ant mislabels Surface as Board search",
    purposes: [],
  },
  {
    id: "contacts-confirm-book-absent",
    module: "Contacts",
    title: "Confirm book for Tower",
    where: "— (named, not interactive on CT)",
    kind: "commit",
    mark: "weak",
    latticeHint: "How consultant-core leaf 2a.1; Furnish Imports",
    notes: "CT shows Hint only — no clickable Confirm",
    purposes: [],
  },
];

export const MEETINGS_PRIORS: PriorEntry[] = [
  {
    id: "meetings-empty-demo",
    module: "Meetings",
    title: "Empty state / Show booked",
    where: "plant+Ant Meetings header toggle",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "CT demo flipper; lattice names empty-state copy not this control",
    purposes: [],
  },
  {
    id: "meetings-brief-close",
    module: "Meetings",
    title: "Close Live brief",
    where: "plant Live brief panel dismiss (when present)",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Dismiss chrome unnamed",
    purposes: [],
  },
];

export const PREPARED_PRIORS: PriorEntry[] = [
  {
    id: "prepared-modal-close",
    module: "Prepared",
    title: "Close Authorize / Accept modal",
    where: "plant+Ant Prepared modals",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Dismiss / Cancel unnamed",
    purposes: [],
  },
  {
    id: "prepared-licensee-select",
    module: "Prepared",
    title: "Licensee identity dropdown",
    where: "plant+Ant Accept terms",
    kind: "select",
    mark: "weak",
    latticeHint: "How leaf 2a.2 identity dropdown",
    notes: "How names the act, not a Title Case surface",
    purposes: [],
  },
];

export const LOGIN_PRIORS: PriorEntry[] = [
  {
    id: "login-change-email",
    module: "Login",
    title: "Change email",
    where: "plant+Ant verify step",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Returns to email step; not in How/Furnish",
    purposes: [],
  },
  {
    id: "login-demo-failure-codes",
    module: "Login",
    title: "Demo OTP failure codes (000000 / 111111)",
    where: "plant+Ant Code field helper",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "CT demo protocol via typed codes",
    purposes: [],
  },
];

export const CONTACT_DESK_PRIORS: PriorEntry[] = [
  {
    id: "contact-portal-surface-nav",
    module: "Contact desk",
    title: "Client portal surface nav (10 touchpoints)",
    where: "plant+Ant Contact aside",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "CT scene flipper among Opt-in…Link state",
    purposes: [],
  },
  {
    id: "contact-link-state-flipper",
    module: "Contact desk",
    title: "Link state · Valid / Expired / Already used / Wrong purpose",
    where: "plant+Ant Link state page Segmented/buttons",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "CT demo flipper to preview Link state outcomes",
    purposes: [],
  },
  {
    id: "contact-link-state-continue",
    module: "Contact desk",
    title: "Continue (Valid path)",
    where: "plant+Ant Link state",
    kind: "nav",
    mark: "weak",
    latticeHint: "Furnish contact-furnish-10 Valid continues to purpose surface",
    notes: "Stub continue; does not route in CT",
    purposes: [],
  },
  {
    id: "contact-purpose-chip-pair",
    module: "Contact desk",
    title: "Client vs Prepared purpose chips (contrast)",
    where: "plant+Ant Link state footer",
    kind: "toggle",
    mark: "weak",
    latticeHint: "Furnish purpose chips",
    notes: "Display contrast pair; not independently actionable",
    purposes: [],
  },
];

export const OPERATOR_ZONE_PRIORS: PriorEntry[] = [
  {
    id: "op-module-nav",
    module: "Operator",
    title: "Operator module sider nav",
    where: "plant+Ant Operator scene Menu/aside",
    kind: "nav",
    mark: "weak",
    latticeHint: "How names each Module as Starting-from",
    notes: "Nav chrome itself unnamed; destinations latticed",
    purposes: [],
  },
  {
    id: "op-section-house-tenancy-support",
    module: "Operator",
    title: "House-global / Per-tenancy / Support section headers",
    where: "plant+Ant Operator sider",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "CT grouping chrome",
    purposes: [],
  },
  {
    id: "op-modal-close",
    module: "Operator",
    title: "Generic modal Close / Cancel / Back",
    where: "plant+Ant across operator modals",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Dismiss chrome",
    purposes: [],
  },
  {
    id: "op-audit-export-csv",
    module: "Operator",
    title: "Download records CSV",
    where: "Ant Book readiness",
    kind: "download",
    mark: "prior",
    latticeHint: "",
    notes: "Also in Audits slice as prior",
    purposes: [],
  },
  {
    id: "op-audit-inspect-first",
    module: "Operator",
    title: "Inspect first record",
    where: "Ant Book readiness",
    kind: "inspect",
    mark: "prior",
    latticeHint: "",
    notes: "Also in Audits slice as prior",
    purposes: [],
  },
  {
    id: "op-audit-sort-records",
    module: "Operator",
    title: "Sort records",
    where: "plant+Ant Audit records",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Also in Audits slice",
    purposes: [],
  },
  {
    id: "op-ads-save-draft",
    module: "Operator",
    title: "Save draft (campaign)",
    where: "Ant AcquisitionAds",
    kind: "commit",
    mark: "weak",
    latticeHint: "How Save / Publish campaign",
    notes: "Draft-save label not in How",
    purposes: [],
  },
  {
    id: "op-ads-staging-queue",
    module: "Operator",
    title: "Staging queue",
    where: "Ant AcquisitionAds",
    kind: "nav",
    mark: "weak",
    latticeHint: "Furnish Waiting-for-hydrate / In-flight",
    notes: "Shortcut label not Title Case lattice",
    purposes: [],
  },
  {
    id: "op-gap-new",
    module: "Operator",
    title: "+ New gap",
    where: "Ant Register evolution",
    kind: "commit",
    mark: "weak",
    latticeHint: "How Save gap / Gaps",
    notes: "Create affordance unnamed as New gap",
    purposes: [],
  },
  {
    id: "op-gap-edit",
    module: "Operator",
    title: "Edit gap",
    where: "Ant Register evolution",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Edit control unnamed",
    purposes: [],
  },
  {
    id: "op-kill-confirm-halt-motion",
    module: "Operator",
    title: "Confirm Halt motion",
    where: "Ant Founder kill-switch",
    kind: "commit",
    mark: "weak",
    latticeHint: "How Kill-switch; Furnish confirmation",
    notes: "Confirm label variant of Halt motion",
    purposes: [],
  },
  {
    id: "op-hifi-empty-fallback",
    module: "Operator",
    title: "HiFi empty module shell",
    where: "plant OperatorPrototypeScene fallback",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Empty Title Case shell when module missing",
    purposes: [],
  },
];

export const GLOBAL_CT_PRIORS: PriorEntry[] = [
  {
    id: "ct-ds-toggle",
    module: "Global CT chrome",
    title: "DS-I | Ant toggle",
    where: "RegisterClickThroughPanel header",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Switches plant vs Ant translate host",
    purposes: [],
  },
  {
    id: "ct-desk-tabs",
    module: "Global CT chrome",
    title: "Consultant / Operator / Contact desk tabs",
    where: "RegisterClickThroughPanel header",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "CT desk switcher",
    purposes: [],
  },
  {
    id: "ct-theme-switch",
    module: "Global CT chrome",
    title: "Light / Dark theme switch",
    where: "Ant PrototypeAntApp Switch; Workspace theme toggle",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "RegisterPage hardcodes isDark=false for plant",
    purposes: [],
  },
  {
    id: "ct-view-as-client",
    module: "Global CT chrome",
    title: "View as Client",
    where: "plant Board row menu inside CT",
    kind: "open",
    mark: "prior",
    latticeHint: "",
    notes: "Same control as Board zone",
    purposes: [],
  },
  {
    id: "ct-meetings-empty-demo",
    module: "Global CT chrome",
    title: "Empty state / Show booked",
    where: "plant+Ant Meetings",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Same as Meetings zone demo flipper",
    purposes: [],
  },
  {
    id: "ct-link-state-flipper",
    module: "Global CT chrome",
    title: "Link state Valid/Expired/Already used/Wrong purpose",
    where: "plant+Ant Contact Link state",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Same as Contact desk demo flipper",
    purposes: [],
  },
  {
    id: "ct-journey-prev-next",
    module: "Global CT chrome",
    title: "Journey Prev / Next / Play",
    where: "RegisterClickThroughPanel flows mode",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Flows pass chrome",
    purposes: [],
  },
  {
    id: "ct-show-hide-columns",
    module: "Global CT chrome",
    title: "Show register / Show theory / Hide CT",
    where: "Register shell chrome",
    kind: "toggle",
    mark: "prior",
    latticeHint: "",
    notes: "Column restore/hide",
    purposes: [],
  },
  {
    id: "ct-ant-source-plant-link",
    module: "Global CT chrome",
    title: "Source plant link",
    where: "Ant PrototypeAntApp header",
    kind: "nav",
    mark: "prior",
    latticeHint: "",
    notes: "Full-document nav back to /register",
    purposes: [],
  },
];

export const DESK_ZONE_PRIORS: PriorEntry[] = [
  ...BOARD_PRIORS,
  ...CONTACTS_PRIORS,
  ...MEETINGS_PRIORS,
  ...PREPARED_PRIORS,
  ...LOGIN_PRIORS,
  ...CONTACT_DESK_PRIORS,
  ...OPERATOR_ZONE_PRIORS,
  ...GLOBAL_CT_PRIORS,
];
