import type { PriorEntry, PriorZone, PriorZoneMeta } from "./types";

/** Full-app priors-only inventory (desk→lattice: no How/SME/Enrichment/Furnish click-path). */
export const ALL_PRIOR_ENTRIES: PriorEntry[] = [
  {
    id: "board-view-as-client",
    zone: "Consultant",
    title: "View as Client",
    where: "plant BoardPanel row ⋯ menu (sarah)",
    kind: "open",
    notes: "Unwired no-op in CT scene; Ant has no row menu",
    purposes: [],
  },
  {
    id: "board-row-actions-menu",
    zone: "Consultant",
    title: "Client actions ⋯",
    where: "plant BoardPanel row menu",
    kind: "menu",
    notes: "Hosts Halt / Resume / View as Client; plant only",
    purposes: [],
  },
  {
    id: "board-resume-book",
    zone: "Consultant",
    title: "Resume book",
    where: "plant+Ant Board when firm book halted",
    kind: "commit",
    notes: "Inverse of Halt firm book; not named in How/Furnish",
    purposes: [],
  },
  {
    id: "board-resume-outreach",
    zone: "Consultant",
    title: "Resume outreach",
    where: "plant BoardPanel row menu when contact halted",
    kind: "commit",
    notes: "Inverse of Halt outreach; plant only",
    purposes: [],
  },
  {
    id: "board-lift-halt",
    zone: "Consultant",
    title: "Lift halt",
    where: "plant+Ant Client workspace (also Engagement record seat)",
    kind: "commit",
    notes: "Inverse of Halt; Enrichment cons-cant-04 Need + surfaceCatalog label only — no How/SME/Furnish click-path",
    purposes: [],
  },
  {
    id: "board-halt-modal-dismiss",
    zone: "Consultant",
    title: "Halt outreach dismiss (backdrop / Cancel)",
    where: "plant+Ant Halt modal",
    kind: "nav",
    notes: "Modal dismiss unnamed",
    purposes: [],
  },
  {
    id: "board-view-in-activity",
    zone: "Consultant",
    title: "View in Activity",
    where: "plant PhaseTooltip on Client row",
    kind: "open",
    notes: "Opens Engagement record; title absent from How/Furnish/Enrichment/SME",
    purposes: [],
  },
  {
    id: "board-clients-collapse",
    zone: "Consultant",
    title: "Clients section expand / collapse",
    where: "plant BoardPanel ClientsSectionHeader",
    kind: "toggle",
    notes: "Section chrome; plant only",
    purposes: [],
  },
  {
    id: "board-tasks-collapse",
    zone: "Consultant",
    title: "Tasks section expand / collapse",
    where: "plant BoardPanel TasksBody",
    kind: "toggle",
    notes: "Tasks absent from consultant How/Furnish",
    purposes: [],
  },
  {
    id: "board-task-row",
    zone: "Consultant",
    title: "Task row open",
    where: "plant BoardPanel TaskRow",
    kind: "open",
    notes: "onTaskClick noop in CT scene",
    purposes: [],
  },
  {
    id: "board-task-status",
    zone: "Consultant",
    title: "Task status toggle",
    where: "plant BoardPanel TaskStatusToggle",
    kind: "commit",
    notes: "Completes/reopens task; not latticed",
    purposes: [],
  },
  {
    id: "board-holon-inspect",
    zone: "Consultant",
    title: "Inspect holons (logo)",
    where: "plant ActivityBarHeader",
    kind: "toggle",
    notes: "CT/docs tooling on consultant Board",
    purposes: [],
  },
  {
    id: "board-console-toggle",
    zone: "Consultant",
    title: "Console",
    where: "plant ActivityBarHeader",
    kind: "toggle",
    notes: "Wired to noop onToggleConsole in CT scene",
    purposes: [],
  },
  {
    id: "board-more-views",
    zone: "Consultant",
    title: "More views menu",
    where: "plant ActivityBarHeader",
    kind: "menu",
    notes: "Opens overflow nav",
    purposes: [],
  },
  {
    id: "board-more-clients",
    zone: "Consultant",
    title: "More views → Clients",
    where: "plant ActivityBarHeader more menu",
    kind: "nav",
    notes: "Unwired stub id",
    purposes: [],
  },
  {
    id: "board-more-account",
    zone: "Consultant",
    title: "More views → Account",
    where: "plant ActivityBarHeader more menu",
    kind: "nav",
    notes: "Unwired stub id",
    purposes: [],
  },
  {
    id: "board-more-settings",
    zone: "Consultant",
    title: "More views → Settings",
    where: "plant ActivityBarHeader more menu",
    kind: "nav",
    notes: "Unwired stub id",
    purposes: [],
  },
  {
    id: "board-list-workspace-resize",
    zone: "Consultant",
    title: "Pane resize (Board/Contacts list ↔ workspace)",
    where: "Ant BoardModule + ContactsModule Splitter",
    kind: "resize",
    notes: "Ant only; layout chrome unnamed",
    purposes: [],
  },
  {
    id: "contacts-search",
    zone: "Consultant",
    title: "Search contacts",
    where: "Ant ContactsModule Input.Search",
    kind: "open",
    notes: "Plant contacts list has no search; Ant mislabels Surface as Board search",
    purposes: [],
  },
  {
    id: "contacts-add-contact",
    zone: "Consultant",
    title: "Add contact",
    where: "plant ContactsSectionHeader +",
    kind: "commit",
    notes: "Stub button (no handler)",
    purposes: [],
  },
  {
    id: "contacts-sort-contacts",
    zone: "Consultant",
    title: "Sort contacts",
    where: "plant ContactsSectionHeader sort",
    kind: "toggle",
    notes: "Stub button (no handler)",
    purposes: [],
  },
  {
    id: "contacts-add-import",
    zone: "Consultant",
    title: "Add import",
    where: "plant ImportsSectionHeader +",
    kind: "commit",
    notes: "Stub button (no handler)",
    purposes: [],
  },
  {
    id: "contacts-sort-imports",
    zone: "Consultant",
    title: "Sort imports",
    where: "plant ImportsSectionHeader sort",
    kind: "toggle",
    notes: "Stub button (no handler)",
    purposes: [],
  },
  {
    id: "meetings-empty-demo",
    zone: "Consultant",
    title: "Empty state / Show booked",
    where: "plant+Ant Meetings header",
    kind: "toggle",
    notes: "CT demo flipper; lattice names empty-state copy, not this control",
    purposes: [],
  },
  {
    id: "meetings-brief-close",
    zone: "Consultant",
    title: "Close / toggle Live brief",
    where: "plant MeetingsModule Live brief button",
    kind: "nav",
    notes: "Open path latticed; dismiss/toggle-off unnamed",
    purposes: [],
  },
  {
    id: "meetings-list-detail-resize",
    zone: "Consultant",
    title: "Pane resize (Meetings list ↔ detail)",
    where: "Ant MeetingsModule Splitter",
    kind: "resize",
    notes: "Ant only",
    purposes: [],
  },
  {
    id: "prepared-modal-close",
    zone: "Consultant",
    title: "Close Authorize / Accept modal",
    where: "plant+Ant Prepared modals (× / Cancel / backdrop)",
    kind: "nav",
    notes: "Dismiss chrome unnamed",
    purposes: [],
  },
  {
    id: "login-change-email",
    zone: "Consultant",
    title: "Change email",
    where: "plant+Ant Login verify step",
    kind: "nav",
    notes: "Returns to email step; not in How/Furnish",
    purposes: [],
  },
  {
    id: "brief-open-client-data",
    zone: "Consultant",
    title: "Open Client Data in new tab",
    where: "plant ClientView DataPanel (Client Brief)",
    kind: "open",
    notes: "External-link control; not in lattice",
    purposes: [],
  },
  {
    id: "ac-client-data-information",
    zone: "Consultant",
    title: "Client Data → Information tab",
    where: "plant ClientDataContent (Brief + Engagement record mounts)",
    kind: "tab",
    notes: "Product holon tab; not consultant How/Furnish",
    purposes: [],
  },
  {
    id: "ac-client-data-history",
    zone: "Consultant",
    title: "Client Data → History tab",
    where: "plant ClientDataContent (Brief + Engagement record mounts)",
    kind: "tab",
    notes: "Product holon tab; not consultant How/Furnish",
    purposes: [],
  },
  {
    id: "ac-crs-history-scrub",
    zone: "Consultant",
    title: "CRS History scrubber",
    where: "plant ClientDataContent History tab",
    kind: "toggle",
    notes: "Scrub index on CRS chart; plant only",
    purposes: [],
  },
  {
    id: "ac-show-reasoning",
    zone: "Consultant",
    title: "Show / Hide reasoning",
    where: "plant JourneyTab ReasoningToggle",
    kind: "toggle",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "ac-inspector-tabs",
    zone: "Consultant",
    title: "Node inspector Overview / Metadata tabs",
    where: "plant EngagementNodePanel",
    kind: "tab",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "ac-inspector-close",
    zone: "Consultant",
    title: "Close node inspector",
    where: "plant EngagementNodePanel",
    kind: "nav",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "ac-inspector-prev-next",
    zone: "Consultant",
    title: "Node inspector Prev / Next",
    where: "plant EngagementNodePanel",
    kind: "nav",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "ac-zoom-in",
    zone: "Consultant",
    title: "Zoom in (day axis)",
    where: "plant JourneyTab + Ant ActivityTimeline",
    kind: "zoom",
    notes: "Product gantt chrome",
    purposes: [],
  },
  {
    id: "ac-zoom-out",
    zone: "Consultant",
    title: "Zoom out (day axis)",
    where: "plant JourneyTab + Ant ActivityTimeline",
    kind: "zoom",
    notes: "Product gantt chrome",
    purposes: [],
  },
  {
    id: "ac-scroll-today",
    zone: "Consultant",
    title: "Scroll to today / Today",
    where: "plant JourneyTab Today button",
    kind: "scroll",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "ac-pane-resize",
    zone: "Consultant",
    title: "Pane resize (list ↔ timeline)",
    where: "plant JourneyTab drag handle + Ant Splitter",
    kind: "resize",
    notes: "Engagement record dual-pane",
    purposes: [],
  },
  {
    id: "ac-gantt-segment",
    zone: "Consultant",
    title: "Timeline segment / marker click",
    where: "plant JourneyTab NudgeGantt segments",
    kind: "open",
    notes: "Ant bars are tooltips only (non-click)",
    purposes: [],
  },
  {
    id: "ac-reveal-thought",
    zone: "Consultant",
    title: "Reveal escalation thought",
    where: "plant JourneyTab nudge escalation row",
    kind: "toggle",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "contact-portal-surface-nav",
    zone: "Contact",
    title: "Client portal surface nav (10 touchpoints)",
    where: "plant+Ant Contact aside Menu/buttons",
    kind: "nav",
    notes: "CT scene flipper among Opt-in…Link state; not contact-facing",
    purposes: [],
  },
  {
    id: "contact-link-state-flipper",
    zone: "Contact",
    title: "Link state · Valid / Expired / Already used / Wrong purpose",
    where: "plant+Ant Link state Segmented/buttons",
    kind: "toggle",
    notes: "CT demo flipper; Furnish names redeem outcomes, not desk toggles",
    purposes: [],
  },
  {
    id: "contact-demo-cem-channel",
    zone: "Contact",
    title: "Demo · EMAIL / Demo · SMS",
    where: "plant+Ant Opt-in message + Nudge message",
    kind: "toggle",
    notes: "CT channel preview; lattice names SMS STOP strip, not Demo toggle",
    purposes: [],
  },
  {
    id: "contact-demo-clear-outstanding",
    zone: "Contact",
    title: "Demo · clear outstanding",
    where: "plant+Ant Booking (facts-not-on-file branch)",
    kind: "toggle",
    notes: "CT demo to flip Facts already on file",
    purposes: [],
  },
  {
    id: "contact-ant-walk",
    zone: "Contact",
    title: "Walk: consent → booking → silence / Next walk step",
    where: "Ant ContactAntScene ModulePage",
    kind: "nav",
    notes: "Ant-only CT walk chrome",
    purposes: [],
  },
  {
    id: "contact-silence-modal-dismiss",
    zone: "Contact",
    title: "Silence confirm Cancel / backdrop",
    where: "Ant Silence / Opt out Modal",
    kind: "nav",
    notes: "Dismiss unnamed; Confirm Silence latticed by How",
    purposes: [],
  },
  {
    id: "ct-ds-toggle",
    zone: "Global CT chrome",
    title: "DS-I | Ant toggle",
    where: "RegisterClickThroughPanel header",
    kind: "toggle",
    notes: "Switches plant vs Ant translate host",
    purposes: [],
  },
  {
    id: "ct-desk-tabs",
    zone: "Global CT chrome",
    title: "Consultant / Operator / Contact desk tabs",
    where: "RegisterClickThroughPanel; Ant PrototypeAntApp Segmented",
    kind: "nav",
    notes: "CT desk switcher",
    purposes: [],
  },
  {
    id: "ct-theme-switch",
    zone: "Global CT chrome",
    title: "Light / Dark theme switch",
    where: "Ant PrototypeAntApp Switch; Workspace theme toggle",
    kind: "toggle",
    notes: "RegisterPage hardcodes isDark=false for plant CT",
    purposes: [],
  },
  {
    id: "ct-journey-prev-next",
    zone: "Global CT chrome",
    title: "Journey Prev / Next / Play",
    where: "RegisterClickThroughPanel flows mode",
    kind: "nav",
    notes: "Flows pass chrome",
    purposes: [],
  },
  {
    id: "ct-show-hide-columns",
    zone: "Global CT chrome",
    title: "Show register / Show theory / Hide CT (+ restore dock)",
    where: "Register shell chrome",
    kind: "toggle",
    notes: "Column restore/hide tooling",
    purposes: [],
  },
  {
    id: "ct-ant-source-plant-link",
    zone: "Global CT chrome",
    title: "Source plant link",
    where: "Ant PrototypeAntApp header",
    kind: "nav",
    notes: "Full-document nav back to /register",
    purposes: [],
  },
  {
    id: "auto-compare-close",
    zone: "Automations",
    title: "Close compare",
    where: "Config libraries · Compare versions modal",
    kind: "nav",
    notes: "plant+Ant dismiss",
    purposes: [],
  },
  {
    id: "auto-rename",
    zone: "Automations",
    title: "Rename automation",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "plant+Ant",
    purposes: [],
  },
  {
    id: "auto-share",
    zone: "Automations",
    title: "Share workflow",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "plant only; unwired",
    purposes: [],
  },
  {
    id: "auto-save",
    zone: "Automations",
    title: "Save",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "plant+Ant; not Publish",
    purposes: [],
  },
  {
    id: "auto-launch",
    zone: "Automations",
    title: "Launch workflow / Stop run",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "Ant Stop; plant Launch stubbed",
    purposes: [],
  },
  {
    id: "auto-tab-runs",
    zone: "Automations",
    title: "Runs tab",
    where: "Editor tabs",
    kind: "tab",
    notes: "plant+Ant",
    purposes: [],
  },
  {
    id: "auto-tab-settings",
    zone: "Automations",
    title: "Settings tab",
    where: "Editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    purposes: [],
  },
  {
    id: "auto-tab-enrollment",
    zone: "Automations",
    title: "Enrollment tab",
    where: "Editor tabs",
    kind: "tab",
    notes: "plant only",
    purposes: [],
  },
  {
    id: "auto-build-toggle",
    zone: "Automations",
    title: "Show / hide Build panel",
    where: "Editor tabs chrome",
    kind: "toggle",
    notes: "plant only",
    purposes: [],
  },
  {
    id: "auto-node-manual-run",
    zone: "Automations",
    title: "Run / Stop manual trigger (node)",
    where: "Trigger node",
    kind: "commit",
    notes: "plant only",
    purposes: [],
  },
  {
    id: "auto-enrollment-filter",
    zone: "Automations",
    title: "Edit class filter",
    where: "Enrollment criteria · class row",
    kind: "open",
    notes: "plant pencil",
    purposes: [],
  },
  {
    id: "auto-class-filter-done",
    zone: "Automations",
    title: "Done (class filter)",
    where: "Filter configuration panel",
    kind: "commit",
    notes: "plant only",
    purposes: [],
  },
  {
    id: "auto-toolbar-attach",
    zone: "Automations",
    title: "Add connected step",
    where: "Node toolbar",
    kind: "menu",
    notes: "plant only",
    purposes: [],
  },
  {
    id: "auto-toolbar-duplicate",
    zone: "Automations",
    title: "Duplicate node",
    where: "Node toolbar",
    kind: "commit",
    notes: "plant only",
    purposes: [],
  },
  {
    id: "auto-toolbar-delete",
    zone: "Automations",
    title: "Delete node",
    where: "Node toolbar",
    kind: "commit",
    notes: "plant only",
    purposes: [],
  },
  {
    id: "auto-edge-insert",
    zone: "Automations",
    title: "Insert step on edge",
    where: "Canvas edge",
    kind: "commit",
    notes: "plant",
    purposes: [],
  },
  {
    id: "auto-attach-pick-block",
    zone: "Automations",
    title: "Attach / insert menu · pick block",
    where: "Attach / Edge insert menu",
    kind: "menu",
    notes: "plant",
    purposes: [],
  },
  {
    id: "auto-attach-branch-handle",
    zone: "Automations",
    title: "Branch handle true / false",
    where: "Attach step menu",
    kind: "toggle",
    notes: "plant",
    purposes: [],
  },
  {
    id: "auto-attach-close",
    zone: "Automations",
    title: "Close attach / insert menu",
    where: "Attach / Edge insert menu",
    kind: "nav",
    notes: "plant",
    purposes: [],
  },
  {
    id: "auto-config-run",
    zone: "Automations",
    title: "Run node",
    where: "Node config modal",
    kind: "commit",
    notes: "plant",
    purposes: [],
  },
  {
    id: "auto-config-close",
    zone: "Automations",
    title: "Close node config",
    where: "Config modal / Ant Drawer",
    kind: "nav",
    notes: "plant+Ant",
    purposes: [],
  },
  {
    id: "auto-config-view-code",
    zone: "Automations",
    title: "View code / Hide code",
    where: "Config · Rule outcomes",
    kind: "toggle",
    notes: "plant",
    purposes: [],
  },
  {
    id: "auto-canvas-controls",
    zone: "Automations",
    title: "Canvas zoom / fit controls",
    where: "Workflow canvas",
    kind: "zoom",
    notes: "plant+Ant",
    purposes: [],
  },
  {
    id: "auto-ant-palette-collapse",
    zone: "Automations",
    title: "Build palette section collapse",
    where: "Ant Build aside",
    kind: "toggle",
    notes: "Ant only",
    purposes: [],
  },
  {
    id: "ag-tab-contacts",
    zone: "Agents",
    title: "Contacts tab",
    where: "Agent editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    purposes: [],
  },
  {
    id: "ag-tab-activity",
    zone: "Agents",
    title: "Activity tab (agent-local)",
    where: "Agent editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    purposes: [],
  },
  {
    id: "ag-tab-report",
    zone: "Agents",
    title: "Report tab",
    where: "Agent editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    purposes: [],
  },
  {
    id: "ag-launch-agent",
    zone: "Agents",
    title: "Launch agent",
    where: "Agent header",
    kind: "commit",
    notes: "plant+Ant stub",
    purposes: [],
  },
  {
    id: "ag-more-actions",
    zone: "Agents",
    title: "More actions menu",
    where: "plant AgentHeader ⋯",
    kind: "menu",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-add-contacts",
    zone: "Agents",
    title: "Add contacts",
    where: "plant More actions item",
    kind: "commit",
    notes: "plant stub",
    purposes: [],
  },
  {
    id: "ag-linked-automations",
    zone: "Agents",
    title: "Linked automations peek",
    where: "plant AgentHeader Zap",
    kind: "open",
    notes: "plant HoverCard",
    purposes: [],
  },
  {
    id: "ag-save-changes",
    zone: "Agents",
    title: "Save changes",
    where: "plant step toolbar",
    kind: "commit",
    notes: "plant stub",
    purposes: [],
  },
  {
    id: "ag-empty-select-template",
    zone: "Agents",
    title: "Select a template (empty state)",
    where: "plant AgentEditorEmptyState",
    kind: "open",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-empty-ai-assisted",
    zone: "Agents",
    title: "AI-assisted agent (empty state)",
    where: "plant AgentEditorEmptyState",
    kind: "open",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-collapse-step",
    zone: "Agents",
    title: "Collapse / expand step",
    where: "plant step frame + rail",
    kind: "toggle",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-more-step-actions",
    zone: "Agents",
    title: "More step actions",
    where: "plant step frame ⋯",
    kind: "menu",
    notes: "plant unwired",
    purposes: [],
  },
  {
    id: "ag-reorder-step",
    zone: "Agents",
    title: "Move step up / down",
    where: "Ant StepCard arrows",
    kind: "reorder",
    notes: "Ant only",
    purposes: [],
  },
  {
    id: "ag-email-compose-tabs",
    zone: "Agents",
    title: "Email Assisted / Prompt / Template tabs",
    where: "plant EmailStepNode",
    kind: "tab",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-email-thread-type",
    zone: "Agents",
    title: "Email thread type (New / Reply)",
    where: "plant EmailStepNode select",
    kind: "select",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-email-preview-refresh",
    zone: "Agents",
    title: "Refresh preview",
    where: "plant EmailStepNode",
    kind: "open",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-email-preview-desktop",
    zone: "Agents",
    title: "Desktop preview",
    where: "plant EmailStepNode",
    kind: "toggle",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-email-preview-mobile",
    zone: "Agents",
    title: "Mobile preview",
    where: "plant EmailStepNode",
    kind: "toggle",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-email-preview-options",
    zone: "Agents",
    title: "Preview options",
    where: "plant EmailStepNode",
    kind: "menu",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-task-priority",
    zone: "Agents",
    title: "Task priority select",
    where: "plant TaskStepNode",
    kind: "select",
    notes: "plant",
    purposes: [],
  },
  {
    id: "ag-task-skip-after",
    zone: "Agents",
    title: "Skip after days checkbox + days",
    where: "plant TaskStepNode",
    kind: "checkbox",
    notes: "plant",
    purposes: [],
  },
  {
    id: "au-sort-records",
    zone: "Audits",
    title: "Sort records",
    where: "Audit run · Records toolbar",
    kind: "toggle",
    notes: "plant+Ant",
    purposes: [],
  },
  {
    id: "au-inspect-record",
    zone: "Audits",
    title: "Inspect record",
    where: "Audit run · Records toolbar (+ Ant eye)",
    kind: "inspect",
    notes: "plant+Ant",
    purposes: [],
  },
  {
    id: "au-export-download-records",
    zone: "Audits",
    title: "Export / Download records CSV",
    where: "Audit run · Records toolbar",
    kind: "download",
    notes: "plant+Ant",
    purposes: [],
  },
  {
    id: "au-select-record-row",
    zone: "Audits",
    title: "Select / highlight record row",
    where: "Ant Records table onRow",
    kind: "open",
    notes: "Ant only",
    purposes: [],
  },
  {
    id: "op-section-house-tenancy-support",
    zone: "Operator house",
    title: "House-global / Per-tenancy / Support section headers",
    where: "plant+Ant Operator sider",
    kind: "nav",
    notes: "Grouping chrome",
    purposes: [],
  },
  {
    id: "op-modal-close",
    zone: "Operator house",
    title: "Modal/drawer Close · Cancel · Back · mask/X dismiss",
    where: "plant+Ant operator modals & drawers",
    kind: "nav",
    notes: "Shared dismiss class",
    purposes: [],
  },
  {
    id: "op-gap-edit",
    zone: "Operator house",
    title: "Edit gap / Edit",
    where: "plant+Ant RegisterEvolutionModule",
    kind: "open",
    notes: "How names New/Save gap — not Edit",
    purposes: [],
  },
  {
    id: "op-review-confirmation",
    zone: "Operator house",
    title: "Review confirmation",
    where: "plant+Ant FounderAgencyControls Kill-switch",
    kind: "nav",
    notes: "Steps into confirmation; Halt motion latticed",
    purposes: [],
  },
  {
    id: "op-kill-apply",
    zone: "Operator house",
    title: "Apply",
    where: "plant+Ant AcquisitionAds Kill / hold criteria",
    kind: "commit",
    notes: "Apply commit unlabeled",
    purposes: [],
  },
  {
    id: "op-activation-firm-row",
    zone: "Operator house",
    title: "Firms in activation row select",
    where: "plant+Ant ActivationStateModule",
    kind: "open",
    notes: "Firm list select unnamed",
    purposes: [],
  },
  {
    id: "op-firm-health-firm-select",
    zone: "Operator house",
    title: "Firm scope select",
    where: "plant+Ant FirmHealthModule",
    kind: "select",
    notes: "Scope when sticky filter absent",
    purposes: [],
  },
  {
    id: "op-hifi-empty-fallback",
    zone: "Operator house",
    title: "HiFi empty module shell",
    where: "plant OperatorPrototypeScene → HiFiEmptyModule",
    kind: "shell",
    notes: "Empty fallback",
    purposes: [],
  },
];

/** Left-tree zone order for the Priors pass. */
export const PRIOR_ZONE_ORDER: PriorZone[] = [
  "Consultant",
  "Contact",
  "Global CT chrome",
  "Automations",
  "Agents",
  "Audits",
  "Operator house",
];

export function getPriorsForZone(zone: PriorZone): PriorEntry[] {
  return ALL_PRIOR_ENTRIES.filter((entry) => entry.zone === zone);
}

export function getPriorEntry(id: string): PriorEntry | undefined {
  return ALL_PRIOR_ENTRIES.find((entry) => entry.id === id);
}

export const PRIOR_ZONES: PriorZoneMeta[] = PRIOR_ZONE_ORDER.map((id) => ({
  id,
  label: id,
  count: getPriorsForZone(id).length,
}));

