import type { PriorEntry, PriorZone, PriorZoneMeta } from "./types";

/** Full-app priors-only inventory (desk→lattice: no How/SME/Enrichment/Furnish click-path). */
export const ALL_PRIOR_ENTRIES: PriorEntry[] = [
  {
    id: "board-view-as-client",
    zone: "Consultant",
    title: "View as Client",
    where: "plant BoardPanel row ⋯ menu (sarah)",
    kind: "open",
    notes: "Unwired no-op in CT scene; Ant has no row menu",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/BoardPanel.tsx",
        symbol: "ClientRow",
        locator: "View as Client",
      },
    ],
    purposes: [],
  },
  {
    id: "board-row-actions-menu",
    zone: "Consultant",
    title: "Client actions ⋯",
    where: "plant BoardPanel row menu",
    kind: "menu",
    notes: "Hosts Halt / Resume / View as Client; plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/BoardPanel.tsx",
        symbol: "ClientRow",
        locator: "aria-label=\"Client actions\"",
      },
    ],
    purposes: [],
  },
  {
    id: "board-resume-book",
    zone: "Consultant",
    title: "Resume book",
    where: "plant+Ant Board when firm book halted",
    kind: "commit",
    notes: "Inverse of Halt firm book; not named in How/Furnish",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/HaltOutreachBar.tsx",
        symbol: "HaltOutreachBar",
        locator: "Resume book",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/BoardModule.tsx",
        symbol: "BoardModule",
        locator: "Resume book",
      },
    ],
    purposes: [],
  },
  {
    id: "board-resume-outreach",
    zone: "Consultant",
    title: "Resume outreach",
    where: "plant BoardPanel row menu when contact halted",
    kind: "commit",
    notes: "Inverse of Halt outreach; plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/BoardPanel.tsx",
        symbol: "ClientRow",
        locator: "Resume outreach",
      },
    ],
    purposes: [],
  },
  {
    id: "board-lift-halt",
    zone: "Consultant",
    title: "Lift halt",
    where: "plant+Ant Client workspace (also Engagement record seat)",
    kind: "commit",
    notes: "Inverse of Halt; Enrichment cons-cant-04 Need + surfaceCatalog label only — no How/SME/Furnish click-path",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/ConsultantClientWorkspace.tsx",
        symbol: "ConsultantClientWorkspace",
        locator: "Lift halt",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/ClientWorkspace.tsx",
        symbol: "ClientWorkspace",
        locator: "Lift halt",
      },
    ],
    purposes: [],
  },
  {
    id: "board-halt-modal-dismiss",
    zone: "Consultant",
    title: "Halt outreach dismiss (backdrop / Cancel)",
    where: "plant+Ant Halt modal",
    kind: "nav",
    notes: "Modal dismiss unnamed",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/ConsultantPrototypeScene.tsx",
        symbol: "HaltOutreachModal",
        locator: "Cancel",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/HaltOutreachModal.tsx",
        symbol: "HaltOutreachModal",
        locator: "Cancel",
      },
    ],
    purposes: [],
  },
  {
    id: "board-view-in-activity",
    zone: "Consultant",
    title: "View in Activity",
    where: "plant PhaseTooltip on Client row",
    kind: "open",
    notes: "Opens Engagement record; title absent from How/Furnish/Enrichment/SME",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/PhaseTooltip.tsx",
        symbol: "PhaseTooltip",
        locator: "View in Activity",
      },
    ],
    purposes: [],
  },
  {
    id: "board-clients-collapse",
    zone: "Consultant",
    title: "Clients section expand / collapse",
    where: "plant BoardPanel ClientsSectionHeader",
    kind: "toggle",
    notes: "Section chrome; plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/BoardPanel.tsx",
        symbol: "ClientsSectionHeader",
        locator: "label=\"Clients Section\"",
      },
    ],
    purposes: [],
  },
  {
    id: "board-tasks-collapse",
    zone: "Consultant",
    title: "Tasks section expand / collapse",
    where: "plant BoardPanel TasksBody",
    kind: "toggle",
    notes: "Tasks absent from consultant How/Furnish",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/tasks/TasksSectionHeader.tsx",
        symbol: "TasksSectionHeader",
        locator: "Tasks",
      },
    ],
    purposes: [],
  },
  {
    id: "board-task-row",
    zone: "Consultant",
    title: "Task row open",
    where: "plant BoardPanel TaskRow",
    kind: "open",
    notes: "onTaskClick noop in CT scene",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/tasks/TaskRow.tsx",
        symbol: "TaskRow",
        locator: "opens in Activity",
      },
    ],
    purposes: [],
  },
  {
    id: "board-task-status",
    zone: "Consultant",
    title: "Task status toggle",
    where: "plant BoardPanel TaskStatusToggle",
    kind: "commit",
    notes: "Completes/reopens task; not latticed",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/tasks/TaskStatusToggle.tsx",
        symbol: "TaskStatusToggle",
        locator: "Mark complete",
      },
    ],
    purposes: [],
  },
  {
    id: "board-holon-inspect",
    zone: "Consultant",
    title: "Inspect holons (logo)",
    where: "plant ActivityBarHeader",
    kind: "toggle",
    notes: "CT/docs tooling on consultant Board",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/ActivityBarHeader.tsx",
        symbol: "ActivityBarHeader",
        locator: "Inspect holons",
      },
    ],
    purposes: [],
  },
  {
    id: "board-console-toggle",
    zone: "Consultant",
    title: "Console",
    where: "plant ActivityBarHeader",
    kind: "toggle",
    notes: "Wired to noop onToggleConsole in CT scene",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/ActivityBarHeader.tsx",
        symbol: "ActivityBarHeader",
        locator: "title=\"Console\"",
      },
    ],
    purposes: [],
  },
  {
    id: "board-more-views",
    zone: "Consultant",
    title: "More views menu",
    where: "plant ActivityBarHeader",
    kind: "menu",
    notes: "Opens overflow nav",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/ActivityBarHeader.tsx",
        symbol: "ActivityBarHeader",
        locator: "More views",
      },
    ],
    purposes: [],
  },
  {
    id: "board-more-clients",
    zone: "Consultant",
    title: "More views → Clients",
    where: "plant ActivityBarHeader more menu",
    kind: "nav",
    notes: "Unwired stub id",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/ActivityBarHeader.tsx",
        symbol: "ActivityBarHeader",
        locator: "onIconClick(id)",
      },
      {
        era: "plant",
        file: "src/app/components/docs/primaryNavigationIcons.ts",
        symbol: "REGISTER_ALL_NAV",
        locator: "label: \"Clients\"",
      },
    ],
    purposes: [],
  },
  {
    id: "board-more-account",
    zone: "Consultant",
    title: "More views → Account",
    where: "plant ActivityBarHeader more menu",
    kind: "nav",
    notes: "Unwired stub id",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/ActivityBarHeader.tsx",
        symbol: "ActivityBarHeader",
        locator: "onIconClick(id)",
      },
      {
        era: "plant",
        file: "src/app/components/docs/primaryNavigationIcons.ts",
        symbol: "REGISTER_ALL_NAV",
        locator: "label: \"Account\"",
      },
    ],
    purposes: [],
  },
  {
    id: "board-more-settings",
    zone: "Consultant",
    title: "More views → Settings",
    where: "plant ActivityBarHeader more menu",
    kind: "nav",
    notes: "Unwired stub id",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/ActivityBarHeader.tsx",
        symbol: "ActivityBarHeader",
        locator: "onIconClick(id)",
      },
      {
        era: "plant",
        file: "src/app/components/docs/primaryNavigationIcons.ts",
        symbol: "REGISTER_ALL_NAV",
        locator: "label: \"Settings\"",
      },
    ],
    purposes: [],
  },
  {
    id: "board-list-workspace-resize",
    zone: "Consultant",
    title: "Pane resize (Board/Contacts list ↔ workspace)",
    where: "Ant BoardModule + ContactsModule Splitter",
    kind: "resize",
    notes: "Ant only; layout chrome unnamed",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/BoardModule.tsx",
        symbol: "BoardModule",
        locator: "<Splitter",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/ContactsModule.tsx",
        symbol: "ContactsModule",
        locator: "<Splitter",
      },
    ],
    purposes: [],
  },
  {
    id: "contacts-search",
    zone: "Consultant",
    title: "Search contacts",
    where: "Ant ContactsModule Input.Search",
    kind: "open",
    notes: "Plant contacts list has no search; Ant mislabels Surface as Board search",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/ContactsModule.tsx",
        symbol: "ContactsModule",
        locator: "Search contacts",
      },
    ],
    purposes: [],
  },
  {
    id: "contacts-add-contact",
    zone: "Consultant",
    title: "Add contact",
    where: "plant ContactsSectionHeader +",
    kind: "commit",
    notes: "Stub button (no handler)",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/contacts/ContactsSectionHeader.tsx",
        symbol: "ContactsSectionHeader",
        locator: "plusTitle=\"Add contact\"",
      },
    ],
    purposes: [],
  },
  {
    id: "contacts-sort-contacts",
    zone: "Consultant",
    title: "Sort contacts",
    where: "plant ContactsSectionHeader sort",
    kind: "toggle",
    notes: "Stub button (no handler)",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/contacts/ContactsSectionHeader.tsx",
        symbol: "ContactsSectionHeader",
        locator: "sortTitle=\"Sort contacts\"",
      },
    ],
    purposes: [],
  },
  {
    id: "contacts-add-import",
    zone: "Consultant",
    title: "Add import",
    where: "plant ImportsSectionHeader +",
    kind: "commit",
    notes: "Stub button (no handler)",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/imports/CsvImportFlow.tsx",
        symbol: "CsvImportFlow",
        locator: "aria-label=\"Add import\"",
      },
    ],
    purposes: [],
  },
  {
    id: "contacts-sort-imports",
    zone: "Consultant",
    title: "Sort imports",
    where: "plant ImportsSectionHeader sort",
    kind: "toggle",
    notes: "Stub button (no handler)",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/contacts/ImportsSectionHeader.tsx",
        symbol: "ImportsSectionHeader",
        locator: "sortTitle=\"Sort imports\"",
      },
    ],
    purposes: [],
  },
  {
    id: "meetings-empty-demo",
    zone: "Consultant",
    title: "Empty state / Show booked",
    where: "plant+Ant Meetings header",
    kind: "toggle",
    notes: "CT demo flipper; lattice names empty-state copy, not this control",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/MeetingsModule.tsx",
        symbol: "MeetingsModule",
        locator: "Empty state",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/MeetingsModule.tsx",
        symbol: "MeetingsModule",
        locator: "Empty state",
      },
    ],
    purposes: [],
  },
  {
    id: "meetings-brief-close",
    zone: "Consultant",
    title: "Close / toggle Live brief",
    where: "plant MeetingsModule Live brief button",
    kind: "nav",
    notes: "Open path latticed; dismiss/toggle-off unnamed",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/MeetingsModule.tsx",
        symbol: "MeetingsModule",
        locator: "Live brief",
      },
    ],
    purposes: [],
  },
  {
    id: "meetings-list-detail-resize",
    zone: "Consultant",
    title: "Pane resize (Meetings list ↔ detail)",
    where: "Ant MeetingsModule Splitter",
    kind: "resize",
    notes: "Ant only",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/MeetingsModule.tsx",
        symbol: "MeetingsModule",
        locator: "<Splitter",
      },
    ],
    purposes: [],
  },
  {
    id: "prepared-modal-close",
    zone: "Consultant",
    title: "Close Authorize / Accept modal",
    where: "plant+Ant Prepared modals (× / Cancel / backdrop)",
    kind: "nav",
    notes: "Dismiss chrome unnamed",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/PreparedWorkspaceModule.tsx",
        symbol: "ModalShell",
        locator: "aria-label=\"Close\"",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/PreparedModule.tsx",
        symbol: "PreparedModule",
        locator: "Cancel",
      },
    ],
    purposes: [],
  },
  {
    id: "login-change-email",
    zone: "Consultant",
    title: "Change email",
    where: "plant+Ant Login verify step",
    kind: "nav",
    notes: "Returns to email step; not in How/Furnish",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/RegisterLoginScene.tsx",
        symbol: "RegisterLoginScene",
        locator: "Change email",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/LoginModule.tsx",
        symbol: "LoginModule",
        locator: "Change email",
      },
    ],
    purposes: [],
  },
  {
    id: "brief-open-client-data",
    zone: "Consultant",
    title: "Open Client Data in new tab",
    where: "plant ClientView DataPanel (Client Brief)",
    kind: "open",
    notes: "External-link control; not in lattice",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/DataPanel.tsx",
        symbol: "ClientDataContent",
        locator: "Open Client Data in new tab",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-client-data-information",
    zone: "Consultant",
    title: "Client Data → Information tab",
    where: "plant ClientDataContent (Brief + Engagement record mounts)",
    kind: "tab",
    notes: "Product holon tab; not consultant How/Furnish",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/DataPanel.tsx",
        symbol: "ClientDataContent",
        locator: "onClick={() => setActiveTab(chip.id)}",
      },
      {
        era: "plant",
        file: "src/app/components/docs/clientDataHolons.ts",
        symbol: "PANEL_CHIPS",
        locator: "label: \"Information\"",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-client-data-history",
    zone: "Consultant",
    title: "Client Data → History tab",
    where: "plant ClientDataContent (Brief + Engagement record mounts)",
    kind: "tab",
    notes: "Product holon tab; not consultant How/Furnish",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/DataPanel.tsx",
        symbol: "ClientDataContent",
        locator: "onClick={() => setActiveTab(chip.id)}",
      },
      {
        era: "plant",
        file: "src/app/components/docs/clientDataHolons.ts",
        symbol: "PANEL_CHIPS",
        locator: "label: \"History\"",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-crs-history-scrub",
    zone: "Consultant",
    title: "CRS History scrubber",
    where: "plant ClientDataContent History tab",
    kind: "toggle",
    notes: "Scrub index on CRS chart; plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/DataPanel.tsx",
        symbol: "CrsHistoryTab",
        locator: "type=\"range\"",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-show-reasoning",
    zone: "Consultant",
    title: "Show / Hide reasoning",
    where: "plant JourneyTab ReasoningToggle",
    kind: "toggle",
    notes: "Plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/JourneyTab.tsx",
        symbol: "ReasoningToggle",
        locator: "Show reasoning",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-inspector-tabs",
    zone: "Consultant",
    title: "Node inspector Overview / Metadata tabs",
    where: "plant EngagementNodePanel",
    kind: "tab",
    notes: "Plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/inspector/EngagementNodePanel.tsx",
        symbol: "EngagementNodePanel",
        locator: "label: \"Overview\"",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-inspector-close",
    zone: "Consultant",
    title: "Close node inspector",
    where: "plant EngagementNodePanel",
    kind: "nav",
    notes: "Plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/inspector/EngagementNodePanel.tsx",
        symbol: "EngagementNodePanel",
        locator: "Close (Esc)",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-inspector-prev-next",
    zone: "Consultant",
    title: "Node inspector Prev / Next",
    where: "plant EngagementNodePanel",
    kind: "nav",
    notes: "Plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/inspector/EngagementNodePanel.tsx",
        symbol: "EngagementNodePanel",
        locator: "data.navigation?.prev",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-zoom-in",
    zone: "Consultant",
    title: "Zoom in (day axis)",
    where: "plant JourneyTab + Ant ActivityTimeline",
    kind: "zoom",
    notes: "Product gantt chrome",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/JourneyTab.tsx",
        symbol: "JourneyTab",
        locator: "Zoom in",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/ClientWorkspace.tsx",
        symbol: "ActivityTimeline",
        locator: "ZoomInOutlined",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-zoom-out",
    zone: "Consultant",
    title: "Zoom out (day axis)",
    where: "plant JourneyTab + Ant ActivityTimeline",
    kind: "zoom",
    notes: "Product gantt chrome",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/JourneyTab.tsx",
        symbol: "JourneyTab",
        locator: "Zoom out",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/ClientWorkspace.tsx",
        symbol: "ActivityTimeline",
        locator: "ZoomOutOutlined",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-scroll-today",
    zone: "Consultant",
    title: "Scroll to today / Today",
    where: "plant JourneyTab Today button",
    kind: "scroll",
    notes: "Plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/JourneyTab.tsx",
        symbol: "JourneyTab",
        locator: "scrollToToday",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-pane-resize",
    zone: "Consultant",
    title: "Pane resize (list ↔ timeline)",
    where: "plant JourneyTab drag handle + Ant Splitter",
    kind: "resize",
    notes: "Engagement record dual-pane",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/JourneyTab.tsx",
        symbol: "JourneyTab",
        locator: "onResizeMouseDown",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/consultant/ClientWorkspace.tsx",
        symbol: "ClientWorkspace",
        locator: "<Splitter",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-gantt-segment",
    zone: "Consultant",
    title: "Timeline segment / marker click",
    where: "plant JourneyTab NudgeGantt segments",
    kind: "open",
    notes: "Ant bars are tooltips only (non-click)",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/JourneyTab.tsx",
        symbol: "JourneyTab",
        locator: "onSegmentClick",
      },
    ],
    purposes: [],
  },
  {
    id: "ac-reveal-thought",
    zone: "Consultant",
    title: "Reveal escalation thought",
    where: "plant JourneyTab nudge escalation row",
    kind: "toggle",
    notes: "Plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/JourneyTab.tsx",
        symbol: "ThoughtStepLine",
        locator: "Thought for",
      },
    ],
    purposes: [],
  },
  {
    id: "contact-portal-surface-nav",
    zone: "Contact",
    title: "Client portal surface nav (10 touchpoints)",
    where: "plant+Ant Contact aside Menu/buttons",
    kind: "nav",
    notes: "CT scene flipper among Opt-in…Link state; not contact-facing",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/ContactPrototypeScene.tsx",
        symbol: "ContactPrototypeScene",
        locator: "Client portal",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/contact/ContactAntScene.tsx",
        symbol: "ContactAntScene",
        locator: "CLIENT PORTAL",
      },
    ],
    purposes: [],
  },
  {
    id: "contact-link-state-flipper",
    zone: "Contact",
    title: "Link state · Valid / Expired / Already used / Wrong purpose",
    where: "plant+Ant Link state Segmented/buttons",
    kind: "toggle",
    notes: "CT demo flipper; Furnish names redeem outcomes, not desk toggles",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/ContactPrototypeScene.tsx",
        symbol: "LinkStatePage",
        locator: "Wrong purpose",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/contact/ContactAntScene.tsx",
        symbol: "LinkStatePage",
        locator: "Wrong purpose",
      },
    ],
    purposes: [],
  },
  {
    id: "contact-demo-cem-channel",
    zone: "Contact",
    title: "Demo · EMAIL / Demo · SMS",
    where: "plant+Ant Opt-in message + Nudge message",
    kind: "toggle",
    notes: "CT channel preview; lattice names SMS STOP strip, not Demo toggle",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/ContactPrototypeScene.tsx",
        symbol: "OptInMessage",
        locator: "Demo · ",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/contact/ContactAntScene.tsx",
        symbol: "OptInMessage",
        locator: "Demo · EMAIL",
      },
    ],
    purposes: [],
  },
  {
    id: "contact-demo-clear-outstanding",
    zone: "Contact",
    title: "Demo · clear outstanding",
    where: "plant+Ant Booking (facts-not-on-file branch)",
    kind: "toggle",
    notes: "CT demo to flip Facts already on file",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/ContactPrototypeScene.tsx",
        symbol: "Booking",
        locator: "Demo · clear outstanding",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/contact/ContactAntScene.tsx",
        symbol: "BookingSurface",
        locator: "Demo · clear outstanding",
      },
    ],
    purposes: [],
  },
  {
    id: "contact-ant-walk",
    zone: "Contact",
    title: "Walk: consent → booking → silence / Next walk step",
    where: "Ant ContactAntScene ModulePage",
    kind: "nav",
    notes: "Ant-only CT walk chrome",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/contact/ContactAntScene.tsx",
        symbol: "ContactAntScene",
        locator: "Walk: consent → booking → silence",
      },
    ],
    purposes: [],
  },
  {
    id: "contact-silence-modal-dismiss",
    zone: "Contact",
    title: "Silence confirm Cancel / backdrop",
    where: "Ant Silence / Opt out Modal",
    kind: "nav",
    notes: "Dismiss unnamed; Confirm Silence latticed by How",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/contact/ContactAntScene.tsx",
        symbol: "SilenceOptOut",
        locator: "onCancel",
      },
    ],
    purposes: [],
  },
  {
    id: "ct-ds-toggle",
    zone: "Global CT chrome",
    title: "DS-I | Ant toggle",
    where: "RegisterClickThroughPanel header",
    kind: "toggle",
    notes: "Switches plant vs Ant translate host",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/components/RegisterClickThroughPanel.tsx",
        symbol: "RegisterClickThroughPanel",
        locator: "DS-I",
      },
    ],
    purposes: [],
  },
  {
    id: "ct-desk-tabs",
    zone: "Global CT chrome",
    title: "Consultant / Operator / Contact desk tabs",
    where: "RegisterClickThroughPanel; Ant PrototypeAntApp Segmented",
    kind: "nav",
    notes: "CT desk switcher",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/components/RegisterClickThroughPanel.tsx",
        symbol: "RegisterClickThroughPanel",
        locator: "Consultant",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/PrototypeAntApp.tsx",
        symbol: "PrototypeAntApp",
        locator: "Operator",
      },
    ],
    purposes: [],
  },
  {
    id: "ct-theme-switch",
    zone: "Global CT chrome",
    title: "Light / Dark theme switch",
    where: "Ant PrototypeAntApp Switch; Workspace theme toggle",
    kind: "toggle",
    notes: "RegisterPage hardcodes isDark=false for plant CT",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/Workspace.tsx",
        symbol: "Workspace",
        locator: "Dark mode",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/PrototypeAntApp.tsx",
        symbol: "PrototypeAntApp",
        locator: "checkedChildren=\"Dark\"",
      },
    ],
    purposes: [],
  },
  {
    id: "ct-journey-prev-next",
    zone: "Global CT chrome",
    title: "Journey Prev / Next / Play",
    where: "RegisterClickThroughPanel flows mode",
    kind: "nav",
    notes: "Flows pass chrome",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/components/RegisterClickThroughPanel.tsx",
        symbol: "RegisterClickThroughPanel",
        locator: "Prev",
      },
    ],
    purposes: [],
  },
  {
    id: "ct-show-hide-columns",
    zone: "Global CT chrome",
    title: "Show register / Show theory / Hide CT (+ restore dock)",
    where: "Register shell chrome",
    kind: "toggle",
    notes: "Column restore/hide tooling",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/components/RegisterClickThroughPanel.tsx",
        symbol: "RegisterClickThroughPanel",
        locator: "Show register",
      },
      {
        era: "plant",
        file: "src/app/register/components/RegisterShellChrome.tsx",
        symbol: "RegisterRestoreDock",
        locator: "Restore Register columns",
      },
    ],
    purposes: [],
  },
  {
    id: "ct-ant-source-plant-link",
    zone: "Global CT chrome",
    title: "Source plant link",
    where: "Ant PrototypeAntApp header",
    kind: "nav",
    notes: "Full-document nav back to /register",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/PrototypeAntApp.tsx",
        symbol: "PrototypeAntApp",
        locator: "Source plant",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-compare-close",
    zone: "Automations",
    title: "Close compare",
    where: "Config libraries · Compare versions modal",
    kind: "nav",
    notes: "plant+Ant dismiss",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/operator/ConfigurationLibrariesPanel.tsx",
        symbol: "ConfigurationLibrariesPanel",
        locator: "setCompareOpen(false)",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/ConfigurationLibrariesModule.tsx",
        symbol: "ConfigurationLibrariesModule",
        locator: "setCompareOpen(false)",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-rename",
    zone: "Automations",
    title: "Rename automation",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "plant+Ant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowHeader.tsx",
        symbol: "AutomationWorkflowHeader",
        locator: "Rename automation",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "Automation name",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-share",
    zone: "Automations",
    title: "Share workflow",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "plant only; unwired",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowHeader.tsx",
        symbol: "AutomationWorkflowHeader",
        locator: "Share workflow",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-save",
    zone: "Automations",
    title: "Save",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "plant+Ant; not Publish",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowHeader.tsx",
        symbol: "AutomationWorkflowHeader",
        locator: "onSave",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "handleSave",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-launch",
    zone: "Automations",
    title: "Launch workflow / Stop run",
    where: "Workflow detail / header",
    kind: "commit",
    notes: "Ant Stop; plant Launch stubbed",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowHeader.tsx",
        symbol: "AutomationWorkflowHeader",
        locator: "Launch workflow",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "Stop run",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-tab-runs",
    zone: "Automations",
    title: "Runs tab",
    where: "Editor tabs",
    kind: "tab",
    notes: "plant+Ant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowEditor.tsx",
        symbol: "AutomationWorkflowEditor",
        locator: "label: \"Runs\"",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "label: \"Runs\"",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-tab-settings",
    zone: "Automations",
    title: "Settings tab",
    where: "Editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowEditor.tsx",
        symbol: "AutomationWorkflowEditor",
        locator: "label: \"Settings\"",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "label: \"Settings\"",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-tab-enrollment",
    zone: "Automations",
    title: "Enrollment tab",
    where: "Editor tabs",
    kind: "tab",
    notes: "plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowEditor.tsx",
        symbol: "AutomationWorkflowEditor",
        locator: "label: \"Enrollment\"",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-build-toggle",
    zone: "Automations",
    title: "Show / hide Build panel",
    where: "Editor tabs chrome",
    kind: "toggle",
    notes: "plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowEditor.tsx",
        symbol: "AutomationWorkflowEditor",
        locator: "Hide build panel",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-node-manual-run",
    zone: "Automations",
    title: "Run / Stop manual trigger (node)",
    where: "Trigger node",
    kind: "commit",
    notes: "plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/nodes/TriggerNode.tsx",
        symbol: "TriggerNode",
        locator: "Run manually",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-enrollment-filter",
    zone: "Automations",
    title: "Edit class filter",
    where: "Enrollment criteria · class row",
    kind: "open",
    notes: "plant pencil",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/ManualEnrollmentCriteriaSummary.tsx",
        symbol: "ManualEnrollmentCriteriaSummary",
        locator: "aria-label={`Filter ${row.label}`}",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-class-filter-done",
    zone: "Automations",
    title: "Done (class filter)",
    where: "Filter configuration panel",
    kind: "commit",
    notes: "plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationManualClassFilterPanel.tsx",
        symbol: "AutomationManualClassFilterPanel",
        locator: "Done",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-toolbar-attach",
    zone: "Automations",
    title: "Add connected step",
    where: "Node toolbar",
    kind: "menu",
    notes: "plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/WorkflowNodeToolbar.tsx",
        symbol: "WorkflowNodeToolbar",
        locator: "Add connected step",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-toolbar-duplicate",
    zone: "Automations",
    title: "Duplicate node",
    where: "Node toolbar",
    kind: "commit",
    notes: "plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/WorkflowNodeToolbar.tsx",
        symbol: "WorkflowNodeToolbar",
        locator: "Duplicate node",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-toolbar-delete",
    zone: "Automations",
    title: "Delete node",
    where: "Node toolbar",
    kind: "commit",
    notes: "plant only",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/WorkflowNodeToolbar.tsx",
        symbol: "WorkflowNodeToolbar",
        locator: "Delete node",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-edge-insert",
    zone: "Automations",
    title: "Insert step on edge",
    where: "Canvas edge",
    kind: "commit",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/edges/AutomationInsertEdge.tsx",
        symbol: "AutomationInsertEdge",
        locator: "Insert step",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-attach-pick-block",
    zone: "Automations",
    title: "Attach / insert menu · pick block",
    where: "Attach / Edge insert menu",
    kind: "menu",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AttachStepMenu.tsx",
        symbol: "AttachStepMenu",
        locator: "Add step",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-attach-branch-handle",
    zone: "Automations",
    title: "Branch handle true / false",
    where: "Attach step menu",
    kind: "toggle",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AttachStepMenu.tsx",
        symbol: "AttachStepMenu",
        locator: "([\"true\", \"false\"] as const)",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-attach-close",
    zone: "Automations",
    title: "Close attach / insert menu",
    where: "Attach / Edge insert menu",
    kind: "nav",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AttachStepMenu.tsx",
        symbol: "AttachStepMenu",
        locator: "Cancel",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-config-run",
    zone: "Automations",
    title: "Run node",
    where: "Node config modal",
    kind: "commit",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationNodeConfigModal.tsx",
        symbol: "AutomationNodeConfigModal",
        locator: "onRunNode",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-config-close",
    zone: "Automations",
    title: "Close node config",
    where: "Config modal / Ant Drawer",
    kind: "nav",
    notes: "plant+Ant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationNodeConfigModal.tsx",
        symbol: "AutomationNodeConfigModal",
        locator: "aria-label=\"Close\"",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "Node details",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-config-view-code",
    zone: "Automations",
    title: "View code / Hide code",
    where: "Config · Rule outcomes",
    kind: "toggle",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/RuleOutcomesConfigForm.tsx",
        symbol: "RuleOutcomesConfigForm",
        locator: "View code",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-canvas-controls",
    zone: "Automations",
    title: "Canvas zoom / fit controls",
    where: "Workflow canvas",
    kind: "zoom",
    notes: "plant+Ant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/automation/AutomationWorkflowCanvas.tsx",
        symbol: "AutomationWorkflowCanvas",
        locator: "<Controls showInteractive={false} />",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "<Controls />",
      },
    ],
    purposes: [],
  },
  {
    id: "auto-ant-palette-collapse",
    zone: "Automations",
    title: "Build palette section collapse",
    where: "Ant Build aside",
    kind: "toggle",
    notes: "Ant only",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAutomationWorkbench.tsx",
        symbol: "AntAutomationWorkbench",
        locator: "<Collapse size=\"small\"",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-tab-contacts",
    zone: "Agents",
    title: "Contacts tab",
    where: "Agent editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentEditor.tsx",
        symbol: "AgentEditor",
        locator: "case \"contacts\":",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAgentWorkbench.tsx",
        symbol: "AntAgentWorkbench",
        locator: "contacts:",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-tab-activity",
    zone: "Agents",
    title: "Activity tab (agent-local)",
    where: "Agent editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentEditor.tsx",
        symbol: "AgentEditor",
        locator: "case \"activity\":",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAgentWorkbench.tsx",
        symbol: "AntAgentWorkbench",
        locator: "activity:",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-tab-report",
    zone: "Agents",
    title: "Report tab",
    where: "Agent editor tabs",
    kind: "tab",
    notes: "plant+Ant empty",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentEditor.tsx",
        symbol: "AgentEditor",
        locator: "case \"report\":",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAgentWorkbench.tsx",
        symbol: "AntAgentWorkbench",
        locator: "report:",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-launch-agent",
    zone: "Agents",
    title: "Launch agent",
    where: "Agent header",
    kind: "commit",
    notes: "plant+Ant stub",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentHeader.tsx",
        symbol: "AgentHeader",
        locator: "Launch agent",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAgentWorkbench.tsx",
        symbol: "AntAgentWorkbench",
        locator: "Launch agent",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-more-actions",
    zone: "Agents",
    title: "More actions menu",
    where: "plant AgentHeader ⋯",
    kind: "menu",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentHeader.tsx",
        symbol: "AgentHeader",
        locator: "More actions",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-add-contacts",
    zone: "Agents",
    title: "Add contacts",
    where: "plant More actions item",
    kind: "commit",
    notes: "plant stub",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentHeader.tsx",
        symbol: "AgentHeader",
        locator: "Add contacts",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-linked-automations",
    zone: "Agents",
    title: "Linked automations peek",
    where: "plant AgentHeader Zap",
    kind: "open",
    notes: "plant HoverCard",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentHeader.tsx",
        symbol: "AutomationsControl",
        locator: "Linked automations",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-save-changes",
    zone: "Agents",
    title: "Save changes",
    where: "plant step toolbar",
    kind: "commit",
    notes: "plant stub",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentEditor.tsx",
        symbol: "AgentEditor",
        locator: "Save changes",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-empty-select-template",
    zone: "Agents",
    title: "Select a template (empty state)",
    where: "plant AgentEditorEmptyState",
    kind: "open",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentEditorEmptyState.tsx",
        symbol: "AgentEditorEmptyState",
        locator: "Select a template",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-empty-ai-assisted",
    zone: "Agents",
    title: "AI-assisted agent (empty state)",
    where: "plant AgentEditorEmptyState",
    kind: "open",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/AgentEditorEmptyState.tsx",
        symbol: "AgentEditorEmptyState",
        locator: "AI-assisted agent",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-collapse-step",
    zone: "Agents",
    title: "Collapse / expand step",
    where: "plant step frame + rail",
    kind: "toggle",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/AgentStepFrame.tsx",
        symbol: "AgentStepFrame",
        locator: "Collapse step",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-more-step-actions",
    zone: "Agents",
    title: "More step actions",
    where: "plant step frame ⋯",
    kind: "menu",
    notes: "plant unwired",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/AgentStepFrame.tsx",
        symbol: "AgentStepFrame",
        locator: "More step actions",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-reorder-step",
    zone: "Agents",
    title: "Move step up / down",
    where: "Ant StepCard arrows",
    kind: "reorder",
    notes: "Ant only",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AntAgentWorkbench.tsx",
        symbol: "StepCard",
        locator: "Move step up",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-email-compose-tabs",
    zone: "Agents",
    title: "Email Assisted / Prompt / Template tabs",
    where: "plant EmailStepNode",
    kind: "tab",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/EmailStepNode.tsx",
        symbol: "EmailStepNode",
        locator: "Assisted",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-email-thread-type",
    zone: "Agents",
    title: "Email thread type (New / Reply)",
    where: "plant EmailStepNode select",
    kind: "select",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/EmailStepNode.tsx",
        symbol: "EmailStepNode",
        locator: "New thread",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-email-preview-refresh",
    zone: "Agents",
    title: "Refresh preview",
    where: "plant EmailStepNode",
    kind: "open",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/EmailStepNode.tsx",
        symbol: "EmailStepNode",
        locator: "Refresh preview",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-email-preview-desktop",
    zone: "Agents",
    title: "Desktop preview",
    where: "plant EmailStepNode",
    kind: "toggle",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/EmailStepNode.tsx",
        symbol: "EmailStepNode",
        locator: "Desktop preview",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-email-preview-mobile",
    zone: "Agents",
    title: "Mobile preview",
    where: "plant EmailStepNode",
    kind: "toggle",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/EmailStepNode.tsx",
        symbol: "EmailStepNode",
        locator: "Mobile preview",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-email-preview-options",
    zone: "Agents",
    title: "Preview options",
    where: "plant EmailStepNode",
    kind: "menu",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/EmailStepNode.tsx",
        symbol: "EmailStepNode",
        locator: "Preview options",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-task-priority",
    zone: "Agents",
    title: "Task priority select",
    where: "plant TaskStepNode",
    kind: "select",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/TaskStepNode.tsx",
        symbol: "TaskStepNode",
        locator: "Task priority*",
      },
    ],
    purposes: [],
  },
  {
    id: "ag-task-skip-after",
    zone: "Agents",
    title: "Skip after days checkbox + days",
    where: "plant TaskStepNode",
    kind: "checkbox",
    notes: "plant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/agent/nodes/TaskStepNode.tsx",
        symbol: "TaskStepNode",
        locator: "Skip tasks",
      },
    ],
    purposes: [],
  },
  {
    id: "au-sort-records",
    zone: "Audits",
    title: "Sort records",
    where: "Audit run · Records toolbar",
    kind: "toggle",
    notes: "plant+Ant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/AuditRecordsTable.tsx",
        symbol: "AuditRecordsTable",
        locator: "Sort records",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/BookReadinessModule.tsx",
        symbol: "BookReadinessModule",
        locator: "SortAscendingOutlined",
      },
    ],
    purposes: [],
  },
  {
    id: "au-inspect-record",
    zone: "Audits",
    title: "Inspect record",
    where: "Audit run · Records toolbar (+ Ant eye)",
    kind: "inspect",
    notes: "plant+Ant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/AuditRecordsTable.tsx",
        symbol: "AuditRecordsTable",
        locator: "Inspect record",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/BookReadinessModule.tsx",
        symbol: "BookReadinessModule",
        locator: "Inspect first record",
      },
    ],
    purposes: [],
  },
  {
    id: "au-export-download-records",
    zone: "Audits",
    title: "Export / Download records CSV",
    where: "Audit run · Records toolbar",
    kind: "download",
    notes: "plant+Ant",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/components/hub/AuditRecordsTable.tsx",
        symbol: "AuditRecordsTable",
        locator: "Export records",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/BookReadinessModule.tsx",
        symbol: "BookReadinessModule",
        locator: "Download records CSV",
      },
    ],
    purposes: [],
  },
  {
    id: "au-select-record-row",
    zone: "Audits",
    title: "Select / highlight record row",
    where: "Ant Records table onRow",
    kind: "open",
    notes: "Ant only",
    codeRefs: [
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/BookReadinessModule.tsx",
        symbol: "BookReadinessModule",
        locator: "onRow",
      },
    ],
    purposes: [],
  },
  {
    id: "op-section-house-tenancy-support",
    zone: "Operator house",
    title: "House-global / Per-tenancy / Support section headers",
    where: "plant+Ant Operator sider",
    kind: "nav",
    notes: "Grouping chrome",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/OperatorPrototypeScene.tsx",
        symbol: "OperatorPrototypeScene",
        locator: "House-global",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/OperatorAntScene.tsx",
        symbol: "OperatorAntScene",
        locator: "Per-tenancy",
      },
    ],
    purposes: [],
  },
  {
    id: "op-modal-close",
    zone: "Operator house",
    title: "Modal/drawer Close · Cancel · Back · mask/X dismiss",
    where: "plant+Ant operator modals & drawers",
    kind: "nav",
    notes: "Shared dismiss class",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/operator/operatorChrome.tsx",
        symbol: "operatorModal",
        locator: "Close",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/ActivationForwardDeployModule.tsx",
        symbol: "ActivationForwardDeployModule",
        locator: "Back",
      },
    ],
    purposes: [],
  },
  {
    id: "op-gap-edit",
    zone: "Operator house",
    title: "Edit gap / Edit",
    where: "plant+Ant RegisterEvolutionModule",
    kind: "open",
    notes: "How names New/Save gap — not Edit",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/operator/RegisterEvolutionModule.tsx",
        symbol: "RegisterEvolutionModule",
        locator: "Edit gap",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/RegisterEvolutionModule.tsx",
        symbol: "RegisterEvolutionModule",
        locator: "Edit",
      },
    ],
    purposes: [],
  },
  {
    id: "op-review-confirmation",
    zone: "Operator house",
    title: "Review confirmation",
    where: "plant+Ant FounderAgencyControls Kill-switch",
    kind: "nav",
    notes: "Steps into confirmation; Halt motion latticed",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/operator/FounderAgencyControlsModule.tsx",
        symbol: "FounderAgencyControlsModule",
        locator: "Review confirmation",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/FounderAgencyControlsModule.tsx",
        symbol: "FounderAgencyControlsModule",
        locator: "Review confirmation",
      },
    ],
    purposes: [],
  },
  {
    id: "op-kill-apply",
    zone: "Operator house",
    title: "Apply",
    where: "plant+Ant AcquisitionAds Kill / hold criteria",
    kind: "commit",
    notes: "Apply commit unlabeled",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/operator/AcquisitionAdsModule.tsx",
        symbol: "AcquisitionAdsModule",
        locator: "Apply",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/AcquisitionAdsModule.tsx",
        symbol: "AcquisitionAdsModule",
        locator: "okText=\"Apply\"",
      },
    ],
    purposes: [],
  },
  {
    id: "op-activation-firm-row",
    zone: "Operator house",
    title: "Firms in activation row select",
    where: "plant+Ant ActivationStateModule",
    kind: "open",
    notes: "Firm list select unnamed",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/operator/ActivationStateModule.tsx",
        symbol: "ActivationStateModule",
        locator: "Firms in activation",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/ActivationStateModule.tsx",
        symbol: "ActivationStateModule",
        locator: "type: \"radio\"",
      },
    ],
    purposes: [],
  },
  {
    id: "op-firm-health-firm-select",
    zone: "Operator house",
    title: "Firm scope select",
    where: "plant+Ant FirmHealthModule",
    kind: "select",
    notes: "Scope when sticky filter absent",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/operator/FirmHealthModule.tsx",
        symbol: "FirmHealthModule",
        locator: "Firm scope",
      },
      {
        era: "ant",
        file: "src/app/register/prototype-ant/operator/FirmHealthModule.tsx",
        symbol: "FirmHealthModule",
        locator: "Firm scope",
      },
    ],
    purposes: [],
  },
  {
    id: "op-hifi-empty-fallback",
    zone: "Operator house",
    title: "HiFi empty module shell",
    where: "plant OperatorPrototypeScene → HiFiEmptyModule",
    kind: "shell",
    notes: "Empty fallback",
    codeRefs: [
      {
        era: "plant",
        file: "src/app/register/prototype/HiFiEmptyModule.tsx",
        symbol: "HiFiEmptyModule",
        locator: "Constructing — addressable from click-path",
      },
    ],
    purposes: [],
  },
];

/** Left-tree zone order for the Priors pass. */
export const PRIOR_ZONE_ORDER: PriorZone[] = [
  "Consultant",
  "Contact",
  "Global CT chrome",
  "Automations",
  "Agents",
  "Audits",
  "Operator house",
];

export function getPriorsForZone(zone: PriorZone): PriorEntry[] {
  return ALL_PRIOR_ENTRIES.filter((entry) => entry.zone === zone);
}

export function getPriorEntry(id: string): PriorEntry | undefined {
  return ALL_PRIOR_ENTRIES.find((entry) => entry.id === id);
}

export const PRIOR_ZONES: PriorZoneMeta[] = PRIOR_ZONE_ORDER.map((id) => ({
  id,
  label: id,
  count: getPriorsForZone(id).length,
}));

