import type { PriorZone, PriorZoneMeta, WeakEntry } from "./types";

/** Full-app weak inventory (lattice foothold; control itself unnamed). */
export const ALL_WEAK_ENTRIES: WeakEntry[] = [
  // —— Consultant (9) ——
  {
    id: "board-accepted-terms",
    zone: "Consultant",
    title: "Accepted terms",
    where: "plant+Ant Board chrome + Client workspace",
    kind: "open",
    latticeFoothold:
      "Accept terms / License acknowledgement / Escrow terms — How consultant-core 2a.2; cons-cant-08",
    notes: "Re-open door; no Title Case click-path for this control",
    purposes: [],
  },
  {
    id: "board-phase-filter",
    zone: "Consultant",
    title: "Phase filter (All / Silent / In motion / Meeting-ready / Halted)",
    where: "plant BoardPanel",
    kind: "toggle",
    latticeFoothold: "Board / Phase signal — How; cons-cant-20 Need",
    notes: "Plant only",
    purposes: [],
  },
  {
    id: "board-newest-first",
    zone: "Consultant",
    title: "Newest first / Oldest first",
    where: "Ant BoardModule Segmented",
    kind: "toggle",
    latticeFoothold: "Furnish cons-furnish-06 Newest first on Engagement record",
    notes: "Ant only; mis-seated Board list sort",
    purposes: [],
  },
  {
    id: "board-phase-legend-close",
    zone: "Consultant",
    title: "Close Phase signal legend",
    where: "plant BoardPanel legend panel",
    kind: "nav",
    latticeFoothold: "Furnish cons-furnish-01 Phase signal legend",
    notes: "Open latticed; Close only prose",
    purposes: [],
  },
  {
    id: "contacts-import-file",
    zone: "Consultant",
    title: "Import file…",
    where: "plant CsvImportFlow popover",
    kind: "open",
    latticeFoothold: "Imports — How consultant-core 2a.1; SME crm-02 Land import",
    notes: "Child under Add import Prior host",
    purposes: [],
  },
  {
    id: "contacts-confirm-import",
    zone: "Consultant",
    title: "Confirm import",
    where: "plant CsvImportColumnMappingDialog",
    kind: "commit",
    latticeFoothold: "Imports / SME crm-02 Land import",
    notes: "Title Case ≠ Land import",
    purposes: [],
  },
  {
    id: "ac-why-this-schedule",
    zone: "Consultant",
    title: "Why this schedule / Hide",
    where: "plant JourneyTab ThoughtStrip",
    kind: "toggle",
    latticeFoothold: "Engagement record — How governance 1.1; cons-furnish-06",
    notes: "Distinct from Show reasoning (Prior)",
    purposes: [],
  },
  {
    id: "ac-tree-expand",
    zone: "Consultant",
    title: "Expand / collapse engagement tree nodes",
    where: "plant JourneyTab + Ant Tree",
    kind: "toggle",
    latticeFoothold: "How Engagement record chronology rows",
    notes: "Tree chrome unnamed",
    purposes: [],
  },
  {
    id: "ac-tree-select",
    zone: "Consultant",
    title: "Select chronology / tree node",
    where: "plant+Ant Engagement record tree",
    kind: "open",
    latticeFoothold: "How / C2 Engagement record chronology",
    notes: "Selection → inspector",
    purposes: [],
  },

  // —— Contact (2) ——
  {
    id: "contact-nudge-form-cta",
    zone: "Contact",
    title: "Open Nudge form",
    where: "plant+Ant Nudge message CEM CTA",
    kind: "open",
    latticeFoothold: "How contact-refresh: Nudge message → Nudge form",
    notes: "Path named; CTA unlabeled as surface",
    purposes: [],
  },
  {
    id: "contact-link-state-continue",
    zone: "Contact",
    title: "Continue",
    where: "plant+Ant Link state (Valid)",
    kind: "open",
    latticeFoothold: "Furnish-10 Link state Valid continues",
    notes: "Parent named; Continue button unlabeled",
    purposes: [],
  },

  // —— Automations (7) ——
  {
    id: "auto-tab-workflow",
    zone: "Automations",
    title: "Workflow tab",
    where: "Automation editor tabs plant+Ant",
    kind: "tab",
    latticeFoothold: "How Workflow canvas",
    notes: "canvas latticed; tab unnamed",
    purposes: [],
  },
  {
    id: "auto-add-trigger",
    zone: "Automations",
    title: "Add trigger",
    where: "Empty canvas / Build Triggers plant+Ant",
    kind: "menu",
    latticeFoothold: "How Trigger nodes · Workflow canvas",
    notes: "add control unnamed",
    purposes: [],
  },
  {
    id: "auto-add-block-palette",
    zone: "Automations",
    title: "Add block (palette)",
    where: "Build palette / Ant Build aside",
    kind: "menu",
    latticeFoothold: "How Trigger/Rule/Action nodes",
    notes: "palette add unnamed",
    purposes: [],
  },
  {
    id: "auto-node-configure",
    zone: "Automations",
    title: "Open / configure node",
    where: "Workflow canvas node plant+Ant",
    kind: "open",
    latticeFoothold: "How Workflow canvas · nodes",
    notes: "open/configure unnamed",
    purposes: [],
  },
  {
    id: "auto-enrollment-open",
    zone: "Automations",
    title: "Open enrollment criteria",
    where: "plant Trigger Enrollment criteria",
    kind: "open",
    latticeFoothold: "How enroll-into-template; SME C1/C2",
    notes: "plant open control unnamed",
    purposes: [],
  },
  {
    id: "cfg-compare-ab",
    zone: "Automations",
    title: "Version A / B pickers",
    where: "Compare versions modal plant+Ant",
    kind: "select",
    latticeFoothold: "Enrichment op-cant-18 Compare versions",
    notes: "A/B pickers unnamed",
    purposes: [],
  },
  {
    id: "eval-pack-name",
    zone: "Automations",
    title: "Pack name field",
    where: "Evaluation pack editor plant+Ant",
    kind: "commit",
    latticeFoothold: "How Evaluation pack editor",
    notes: "rename field unnamed",
    purposes: [],
  },

  // —— Agents (7) ——
  {
    id: "ag-tab-editor",
    zone: "Agents",
    title: "Editor tab",
    where: "Agent editor tabs plant+Ant",
    kind: "tab",
    latticeFoothold: "How Agent / sequence editor · Step rail",
    notes: "tab unnamed",
    purposes: [],
  },
  {
    id: "ag-tab-settings",
    zone: "Agents",
    title: "Settings tab",
    where: "Agent editor tabs plant+Ant",
    kind: "tab",
    latticeFoothold: "Step rail / C2 channel-ruleset authorship",
    notes: "Settings unnamed",
    purposes: [],
  },
  {
    id: "ag-add-step",
    zone: "Agents",
    title: "Add a step",
    where: "plant step rail + canvas insert",
    kind: "menu",
    latticeFoothold: "How Step rail / Sequence canvas",
    notes: "menu label unnamed",
    purposes: [],
  },
  {
    id: "ag-add-email",
    zone: "Agents",
    title: "Add email",
    where: "plant Add-a-step; Ant toolbar Email",
    kind: "commit",
    latticeFoothold: "How Step rail",
    notes: "add-email unnamed",
    purposes: [],
  },
  {
    id: "ag-add-consultant-task",
    zone: "Agents",
    title: "Add consultant task",
    where: "plant Add-a-step; Ant toolbar Task",
    kind: "commit",
    latticeFoothold: "How Step rail",
    notes: "add-task unnamed",
    purposes: [],
  },
  {
    id: "ag-toggle-step-rail",
    zone: "Agents",
    title: "Collapse / expand step rail",
    where: "plant AgentEditor step toolbar",
    kind: "toggle",
    latticeFoothold: "How Step rail",
    notes: "show/hide chrome unnamed",
    purposes: [],
  },
  {
    id: "ag-select-step",
    zone: "Agents",
    title: "Select step on canvas / rail",
    where: "plant sequence canvas + step rail",
    kind: "open",
    latticeFoothold: "How Step rail / Sequence canvas",
    notes: "selection chrome unnamed",
    purposes: [],
  },

  // —— Audits (1) ——
  {
    id: "au-run-checks-all",
    zone: "Audits",
    title: "Run checks (select all)",
    where: "plant Audit run services",
    kind: "checkbox",
    latticeFoothold: "How Audit run checkboxes",
    notes: "select-all unnamed",
    purposes: [],
  },

  // —— Operator house (6) ——
  {
    id: "op-module-nav",
    zone: "Operator house",
    title: "Operator module sider nav",
    where: "plant+Ant Operator sider Menu",
    kind: "nav",
    latticeFoothold: "How Starting-from each Module",
    notes: "sider chrome unnamed",
    purposes: [],
  },
  {
    id: "op-ads-save-draft",
    zone: "Operator house",
    title: "Save draft (campaign)",
    where: "plant+Ant AcquisitionAds campaign editor",
    kind: "commit",
    latticeFoothold: "How Save / Publish campaign",
    notes: "secondary draft save",
    purposes: [],
  },
  {
    id: "op-ads-staging-queue",
    zone: "Operator house",
    title: "Staging queue",
    where: "plant+Ant AcquisitionAds",
    kind: "nav",
    latticeFoothold: "Furnish Waiting-for-hydrate → In-flight",
    notes: "card title not lattice Title Case",
    purposes: [],
  },
  {
    id: "op-activation-firm-link",
    zone: "Operator house",
    title: "Firm name link → Forward-deploy drawer",
    where: "Ant ActivationForwardDeploy table",
    kind: "open",
    latticeFoothold: "How In-flight firm row · Forward-deploy",
    notes: "unnamed firm link",
    purposes: [],
  },
  {
    id: "op-activation-row-radio",
    zone: "Operator house",
    title: "In-flight radio select",
    where: "Ant ActivationForwardDeploy Table",
    kind: "select",
    latticeFoothold: "How In-flight activations · firm row",
    notes: "selection chrome",
    purposes: [],
  },
  {
    id: "op-commercial-instrument-radio",
    zone: "Operator house",
    title: "Instrument list radio select",
    where: "Ant CommercialModule instrument Table",
    kind: "select",
    latticeFoothold: "How Instrument list / firm row",
    notes: "selection chrome",
    purposes: [],
  },
];

/** Left-tree zone order for the Weak pass (no Global CT chrome weaks). */
export const WEAK_ZONE_ORDER: PriorZone[] = [
  "Consultant",
  "Contact",
  "Automations",
  "Agents",
  "Audits",
  "Operator house",
];

export function getWeaksForZone(zone: PriorZone): WeakEntry[] {
  return ALL_WEAK_ENTRIES.filter((entry) => entry.zone === zone);
}

export function getWeakEntry(id: string): WeakEntry | undefined {
  return ALL_WEAK_ENTRIES.find((entry) => entry.id === id);
}

export const WEAK_ZONES: PriorZoneMeta[] = WEAK_ZONE_ORDER.map((id) => ({
  id,
  label: id,
  count: getWeaksForZone(id).length,
}));
