import type { HolonRegistration } from "../../context/DocsRegistryContext";

/** Pre-flattened holon catalog for Systems Register — generated by scripts/generate-holon-catalog-flat.mts */
export const HOLON_CATALOG_ENTRIES: HolonRegistration[] = [
  {
    "id": "login-form",
    "label": "Login Form",
    "icon": "user",
    "parentId": null,
    "order": 5,
    "inView": false
  },
  {
    "id": "login-form-banner",
    "label": "Login Form Banner",
    "icon": "information-circle",
    "parentId": "login-form",
    "order": 0,
    "inView": false
  },
  {
    "id": "login-email-field",
    "label": "Email Field",
    "icon": "user",
    "parentId": "login-form",
    "order": 1,
    "inView": false
  },
  {
    "id": "login-submit-control",
    "label": "Log In",
    "icon": "cursor-click",
    "parentId": "login-form",
    "order": 2,
    "inView": false
  },
  {
    "id": "login-verify-code-field",
    "label": "Verification Code Field",
    "icon": "checkmark-list",
    "parentId": "login-form",
    "order": 3,
    "inView": false
  },
  {
    "id": "login-verify-submit-control",
    "label": "Verify Email Address",
    "icon": "cursor-click",
    "parentId": "login-form",
    "order": 4,
    "inView": false
  },
  {
    "id": "primary-navigation",
    "label": "Primary Navigation",
    "icon": "compass",
    "parentId": null,
    "order": 10,
    "inView": false
  },
  {
    "id": "clients-section",
    "label": "Clients Section",
    "icon": "people",
    "parentId": null,
    "order": 40,
    "inView": false
  },
  {
    "id": "board-body",
    "label": "Board Body",
    "icon": "list-bullet",
    "parentId": null,
    "order": 50,
    "inView": false
  },
  {
    "id": "client-row",
    "label": "Client Row",
    "icon": "user",
    "parentId": "board-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "phase-signal",
    "label": "Phase Signal",
    "icon": "lightning-bolt",
    "parentId": "client-row",
    "order": 0,
    "inView": false
  },
  {
    "id": "client-name",
    "label": "Client Name",
    "icon": "tag",
    "parentId": "client-row",
    "order": 1,
    "inView": false
  },
  {
    "id": "row-actions",
    "label": "Row Actions",
    "lucideIcon": "more-horizontal",
    "parentId": "client-row",
    "order": 2,
    "inView": false
  },
  {
    "id": "tasks-section",
    "label": "Tasks Section",
    "icon": "checkmark-list",
    "parentId": null,
    "order": 52,
    "inView": false
  },
  {
    "id": "task-row",
    "label": "Task Row",
    "icon": "pencil-list",
    "parentId": "tasks-section",
    "order": 0,
    "inView": false
  },
  {
    "id": "task-status-toggle",
    "label": "Status Toggle",
    "lucideIcon": "check-square",
    "parentId": "task-row",
    "order": 0,
    "inView": false
  },
  {
    "id": "task-label",
    "label": "Task Label",
    "icon": "document",
    "parentId": "task-row",
    "order": 1,
    "inView": false
  },
  {
    "id": "task-meta",
    "label": "Task Meta",
    "icon": "information-circle",
    "parentId": "task-row",
    "order": 2,
    "inView": false
  },
  {
    "id": "contacts-section",
    "label": "Contacts Section",
    "icon": "user-squares",
    "parentId": null,
    "order": 45,
    "inView": false
  },
  {
    "id": "contacts-body",
    "label": "Contacts Body",
    "icon": "list-bullet",
    "parentId": null,
    "order": 55,
    "inView": false
  },
  {
    "id": "contact-row",
    "label": "Contact Row",
    "icon": "user",
    "parentId": "contacts-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "imports-section",
    "label": "Imports Section",
    "icon": "documents",
    "parentId": "contacts-body",
    "order": 1,
    "inView": false
  },
  {
    "id": "add-import-control",
    "label": "Add Import",
    "icon": "plus",
    "parentId": "imports-section",
    "order": 0,
    "inView": false
  },
  {
    "id": "import-row",
    "label": "Import Row",
    "icon": "document-arrow-up",
    "parentId": "imports-section",
    "order": 0,
    "inView": false
  },
  {
    "id": "import-row",
    "label": "Import Row",
    "icon": "document-arrow-up",
    "parentId": "contacts-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "hub-body",
    "label": "Hub Body",
    "icon": "compass",
    "parentId": null,
    "order": 54,
    "inView": false
  },
  {
    "id": "audits-section",
    "label": "Audits Section",
    "icon": "magnifying-glass",
    "parentId": "hub-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "audit-row",
    "label": "Audit Row",
    "icon": "document",
    "parentId": "hub-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "agents-section",
    "label": "Agents Section",
    "icon": "cursor-click",
    "parentId": "hub-body",
    "order": 1,
    "inView": false
  },
  {
    "id": "agent-row",
    "label": "Agent Row",
    "icon": "user",
    "parentId": "hub-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "automations-section",
    "label": "Automations Section",
    "icon": "lightning-bolt",
    "parentId": "hub-body",
    "order": 2,
    "inView": false
  },
  {
    "id": "automation-row",
    "label": "Automation Row",
    "icon": "circle-dashed",
    "parentId": "hub-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "tab-bar",
    "label": "Tab Bar",
    "icon": "list-bullet",
    "parentId": null,
    "order": 60,
    "inView": false
  },
  {
    "id": "workspace-tab",
    "label": "Workspace Tab",
    "icon": "document",
    "parentId": null,
    "order": 70,
    "inView": false
  },
  {
    "id": "breadcrumb",
    "label": "Breadcrumb",
    "icon": "directional-sign",
    "parentId": null,
    "order": 80,
    "inView": false
  },
  {
    "id": "workspace-empty",
    "label": "Workspace Empty",
    "icon": "document",
    "parentId": null,
    "order": 90,
    "inView": false
  },
  {
    "id": "client-header",
    "label": "Client Header",
    "icon": "user",
    "parentId": null,
    "order": 100,
    "inView": false
  },
  {
    "id": "client-brief",
    "label": "Client Brief",
    "icon": "document",
    "parentId": null,
    "order": 110,
    "inView": false
  },
  {
    "id": "contact-header",
    "label": "Contact Header",
    "icon": "user",
    "parentId": null,
    "order": 115,
    "inView": false
  },
  {
    "id": "contact-record",
    "label": "Contact Record",
    "icon": "checkmark-list",
    "parentId": null,
    "order": 116,
    "inView": false
  },
  {
    "id": "hub-tool-header",
    "label": "Hub Tool Header",
    "icon": "compass",
    "parentId": null,
    "order": 117,
    "inView": false
  },
  {
    "id": "hub-tool-body",
    "label": "Hub Tool Body",
    "icon": "list-bullet",
    "parentId": null,
    "order": 118,
    "inView": false
  },
  {
    "id": "agent-editor",
    "label": "Agent Editor",
    "icon": "user",
    "parentId": "hub-tool-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "agent-header-actions",
    "label": "Agent Actions",
    "icon": "cursor-click",
    "parentId": "agent-editor",
    "order": 0,
    "inView": false
  },
  {
    "id": "agent-editor-tabs",
    "label": "Editor Tabs",
    "icon": "list-bullet",
    "parentId": "agent-editor",
    "order": 0,
    "inView": false
  },
  {
    "id": "agent-editor-tab",
    "label": "Editor Tab",
    "icon": "compass",
    "parentId": "agent-editor-tabs",
    "order": 1,
    "inView": false
  },
  {
    "id": "agent-contacts-tab",
    "label": "Contacts Tab",
    "icon": "people",
    "parentId": "agent-editor-tabs",
    "order": 2,
    "inView": false
  },
  {
    "id": "agent-activity-tab",
    "label": "Activity Tab",
    "icon": "clock",
    "parentId": "agent-editor-tabs",
    "order": 3,
    "inView": false
  },
  {
    "id": "agent-report-tab",
    "label": "Report Tab",
    "icon": "chart-bar-horizontal",
    "parentId": "agent-editor-tabs",
    "order": 4,
    "inView": false
  },
  {
    "id": "agent-settings-tab",
    "label": "Settings Tab",
    "icon": "gear",
    "parentId": "agent-editor-tabs",
    "order": 5,
    "inView": false
  },
  {
    "id": "agent-step-toolbar",
    "label": "Step Toolbar",
    "icon": "dependency",
    "parentId": "agent-editor",
    "order": 0,
    "inView": false
  },
  {
    "id": "agent-empty-state",
    "label": "Empty Agent State",
    "icon": "directional-sign",
    "parentId": "agent-editor",
    "order": 1,
    "inView": false
  },
  {
    "id": "agent-add-step",
    "label": "Add Step Control",
    "icon": "plus",
    "parentId": "agent-empty-state",
    "order": 3,
    "inView": false
  },
  {
    "id": "agent-step-rail",
    "label": "Step Rail",
    "icon": "list",
    "parentId": "agent-editor",
    "order": 2,
    "inView": false
  },
  {
    "id": "agent-sequence-canvas",
    "label": "Sequence Canvas",
    "icon": "compass",
    "parentId": "agent-editor",
    "order": 3,
    "inView": false
  },
  {
    "id": "agent-email-step-node",
    "label": "Email Step Node",
    "icon": "document",
    "parentId": "agent-sequence-canvas",
    "order": 0,
    "inView": false
  },
  {
    "id": "agent-task-step-node",
    "label": "Task Step Node",
    "icon": "checkmark-list",
    "parentId": "agent-sequence-canvas",
    "order": 1,
    "inView": false
  },
  {
    "id": "agent-step-condition",
    "label": "Step Condition",
    "icon": "clock",
    "parentId": "agent-sequence-canvas",
    "order": 2,
    "inView": false
  },
  {
    "id": "agent-add-step",
    "label": "Add Step Control",
    "icon": "plus",
    "parentId": "agent-sequence-canvas",
    "order": 3,
    "inView": false
  },
  {
    "id": "automation-workflow-editor",
    "label": "Workflow Editor",
    "icon": "lightning-bolt",
    "parentId": "hub-tool-body",
    "order": 0,
    "inView": false
  },
  {
    "id": "automation-workflow-actions",
    "label": "Workflow Actions",
    "icon": "cursor-click",
    "parentId": "automation-workflow-editor",
    "order": 0,
    "inView": false
  },
  {
    "id": "automation-editor-tabs",
    "label": "Editor Tabs",
    "icon": "list-bullet",
    "parentId": "automation-workflow-editor",
    "order": 0,
    "inView": false
  },
  {
    "id": "automation-workflow-tab",
    "label": "Workflow Tab",
    "icon": "compass",
    "parentId": "automation-editor-tabs",
    "order": 1,
    "inView": false
  },
  {
    "id": "automation-runs-tab",
    "label": "Runs Tab",
    "icon": "list",
    "parentId": "automation-editor-tabs",
    "order": 2,
    "inView": false
  },
  {
    "id": "automation-settings-tab",
    "label": "Settings Tab",
    "icon": "gear",
    "parentId": "automation-editor-tabs",
    "order": 3,
    "inView": false
  },
  {
    "id": "automation-enrollment-tab",
    "label": "Enrollment Tab",
    "icon": "people",
    "parentId": "automation-editor-tabs",
    "order": 4,
    "inView": false
  },
  {
    "id": "automation-workflow-canvas",
    "label": "Workflow Canvas",
    "icon": "compass",
    "parentId": "automation-workflow-editor",
    "order": 0,
    "inView": false
  },
  {
    "id": "automation-trigger-node",
    "label": "Trigger Node",
    "icon": "lightning-bolt",
    "parentId": "automation-workflow-canvas",
    "order": 0,
    "inView": false
  },
  {
    "id": "automation-branch-node",
    "label": "Branch Node",
    "icon": "filter",
    "parentId": "automation-workflow-canvas",
    "order": 1,
    "inView": false
  },
  {
    "id": "automation-action-node",
    "label": "Action Node",
    "icon": "directional-sign",
    "parentId": "automation-workflow-canvas",
    "order": 2,
    "inView": false
  },
  {
    "id": "automation-exit-node",
    "label": "Exit Node",
    "icon": "dot-circle",
    "parentId": "automation-workflow-canvas",
    "order": 3,
    "inView": false
  },
  {
    "id": "automation-edge-insert",
    "label": "Edge Insert Control",
    "icon": "plus",
    "parentId": "automation-workflow-canvas",
    "order": 4,
    "inView": false
  },
  {
    "id": "automation-build-palette",
    "label": "Build Palette",
    "icon": "wrench",
    "parentId": "automation-workflow-editor",
    "order": 1,
    "inView": false
  },
  {
    "id": "data-panel-header",
    "label": "Client Data Header",
    "icon": "information-circle",
    "parentId": null,
    "order": 120,
    "inView": false
  },
  {
    "id": "client-data-open-tab",
    "label": "Open in Tab",
    "lucideIcon": "external-link",
    "parentId": "data-panel-header",
    "order": -1,
    "inView": false
  },
  {
    "id": "data-panel-tab-read",
    "label": "Information",
    "icon": "information-circle",
    "parentId": "data-panel-header",
    "order": 0,
    "inView": false
  },
  {
    "id": "profile-table",
    "label": "Profile Table",
    "icon": "checkmark-list",
    "parentId": "data-panel-tab-read",
    "order": 0,
    "inView": false
  },
  {
    "id": "data-panel-tab-data",
    "label": "History",
    "icon": "chart-bar-line",
    "parentId": "data-panel-header",
    "order": 1,
    "inView": false
  },
  {
    "id": "crs-history",
    "label": "CRS History",
    "icon": "chart-bar-vertical",
    "parentId": "data-panel-tab-data",
    "inView": false
  },
  {
    "id": "crs-scrubber",
    "label": "CRS Scrubber",
    "icon": "cursor-click",
    "parentId": "crs-history",
    "order": 0,
    "inView": false
  },
  {
    "id": "crs-stats",
    "label": "CRS Stats",
    "icon": "chart-bar-horizontal",
    "parentId": "crs-history",
    "order": 1,
    "inView": false
  },
  {
    "id": "crs-chart",
    "label": "CRS Chart",
    "icon": "chart-bar-line",
    "parentId": "crs-history",
    "order": 2,
    "inView": false
  },
  {
    "id": "data-panel-tab-logs",
    "label": "Activity",
    "icon": "lightning-bolt",
    "parentId": "data-panel-header",
    "order": 2,
    "inView": false
  },
  {
    "id": "activity-panel",
    "label": "Engagement Chart",
    "icon": "lightning-bolt",
    "parentId": "data-panel-tab-logs",
    "inView": false
  },
  {
    "id": "engagement-list",
    "label": "Engagement List",
    "icon": "list",
    "parentId": "activity-panel",
    "order": 0,
    "inView": false
  },
  {
    "id": "engagement-sequence-row",
    "label": "Sequence Row",
    "icon": "tag",
    "parentId": "engagement-list",
    "order": 0,
    "inView": false
  },
  {
    "id": "engagement-channel-row",
    "label": "Channel Row",
    "icon": "directional-sign",
    "parentId": "engagement-list",
    "order": 1,
    "inView": false
  },
  {
    "id": "engagement-form-visit-row",
    "label": "Form Visit Row",
    "icon": "computer-window",
    "parentId": "engagement-list",
    "order": 2,
    "inView": false
  },
  {
    "id": "engagement-event-row",
    "label": "Event Row",
    "icon": "bell",
    "parentId": "engagement-list",
    "order": 3,
    "inView": false
  },
  {
    "id": "engagement-escalation-row",
    "label": "Escalation Row",
    "icon": "lightning-bolt",
    "parentId": "engagement-list",
    "order": 4,
    "inView": false
  },
  {
    "id": "engagement-attempt-row",
    "label": "Attempt Row",
    "icon": "circle-dashed",
    "parentId": "engagement-list",
    "order": 5,
    "inView": false
  },
  {
    "id": "engagement-timeline",
    "label": "Engagement Timeline",
    "icon": "chart-bar-horizontal",
    "parentId": "activity-panel",
    "order": 1,
    "inView": false
  },
  {
    "id": "engagement-sequence-bar",
    "label": "Sequence Bar",
    "icon": "chart-bar-horizontal",
    "parentId": "engagement-timeline",
    "order": 0,
    "inView": false
  },
  {
    "id": "engagement-attempt-band",
    "label": "Attempt Band",
    "icon": "circle-dashed",
    "parentId": "engagement-timeline",
    "order": 1,
    "inView": false
  },
  {
    "id": "engagement-segment-bar",
    "label": "Segment Bar",
    "icon": "directional-sign",
    "parentId": "engagement-timeline",
    "order": 2,
    "inView": false
  },
  {
    "id": "engagement-event-marker",
    "label": "Event Marker",
    "icon": "bell",
    "parentId": "engagement-timeline",
    "order": 3,
    "inView": false
  },
  {
    "id": "engagement-escalation-band",
    "label": "Escalation Band",
    "icon": "lightning-bolt",
    "parentId": "engagement-timeline",
    "order": 4,
    "inView": false
  },
  {
    "id": "status-bar",
    "label": "Status Bar",
    "icon": "information-circle",
    "parentId": null,
    "order": 130,
    "inView": false
  },
  {
    "id": "holon-detail-header",
    "label": "Holon Detail Header",
    "icon": "document",
    "parentId": null,
    "order": 140,
    "inView": false
  },
  {
    "id": "holon-detail-body",
    "label": "Holon Detail Body",
    "icon": "list-bullet",
    "parentId": null,
    "order": 150,
    "inView": false
  },
  {
    "id": "docs-header",
    "label": "Console Header",
    "icon": "document",
    "parentId": null,
    "order": 20,
    "inView": false
  },
  {
    "id": "docs-registry",
    "label": "Console Registry",
    "icon": "list",
    "parentId": null,
    "order": 30,
    "inView": false
  },
  {
    "id": "docs-home-branch",
    "label": "Home",
    "icon": "house",
    "parentId": "docs-registry",
    "order": 0,
    "inView": false
  },
  {
    "id": "docs-panels-branch",
    "label": "Panels",
    "icon": "grid-square-2x2",
    "parentId": "docs-registry",
    "order": 1,
    "inView": false
  },
  {
    "id": "docs-outline-row",
    "label": "Console Outline Row",
    "icon": "list-bullet",
    "parentId": "docs-registry",
    "order": 2,
    "inView": false
  },
  {
    "id": "docs-row-name",
    "label": "Row Name",
    "icon": "tag",
    "parentId": "docs-outline-row",
    "order": 0,
    "inView": false
  },
  {
    "id": "docs-inview-indicator",
    "label": "In-View Indicator",
    "icon": "eye",
    "parentId": "docs-outline-row",
    "order": 1,
    "inView": false
  },
  {
    "id": "docs-row-actions",
    "label": "Row Actions",
    "lucideIcon": "more-horizontal",
    "parentId": "docs-outline-row",
    "order": 2,
    "inView": false
  }
];
