/** Display order for top-level shell holons in the docs Panels tree */
export const SHELL_HOLON_ORDER: Record<string, number> = {
  "primary-navigation": 10,
  "docs-header": 20,
  "docs-registry": 30,
  "clients-section": 40,
  "contacts-section": 45,
  "board-body": 50,
  "contacts-body": 55,
  "imports-section": 56,
  "tab-bar": 60,
  "workspace-tab": 70,
  "breadcrumb": 80,
  "workspace-empty": 90,
  "client-header": 100,
  "client-brief": 110,
  "contact-header": 115,
  "contact-record": 116,
  "data-panel-header": 120,
  "status-bar": 130,
  "holon-detail-header": 140,
  "holon-detail-body": 150,
};
